# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.api.divisions_api import DivisionsApi


class TestDivisionsApi(unittest.TestCase):
    """DivisionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DivisionsApi()

    def tearDown(self) -> None:
        pass

    def test_divisions_get(self) -> None:
        """Test case for divisions_get

        List divisions for the authenticated creditor.
        """
        pass

    def test_divisions_id_archive_post(self) -> None:
        """Test case for divisions_id_archive_post

        Archive a division.
        """
        pass

    def test_divisions_id_delete(self) -> None:
        """Test case for divisions_id_delete

        Delete a division.
        """
        pass

    def test_divisions_id_get(self) -> None:
        """Test case for divisions_id_get

        Get a single division by ID.
        """
        pass

    def test_divisions_id_put(self) -> None:
        """Test case for divisions_id_put

        Update a division.
        """
        pass

    def test_divisions_idarchive_post(self) -> None:
        """Test case for divisions_idarchive_post

        Archive a division.
        """
        pass

    def test_divisions_post(self) -> None:
        """Test case for divisions_post

        Create a new division.
        """
        pass


if __name__ == '__main__':
    unittest.main()
