# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.api.me_api import MeApi


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeApi()

    def tearDown(self) -> None:
        pass

    def test_me_get(self) -> None:
        """Test case for me_get

        Verifies the provided authentication and returns the current Creditor profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
