# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_divisions_division_list_dto import DebituraWebExternalApiContractsV1DivisionsDivisionListDto

class TestDebituraWebExternalApiContractsV1DivisionsDivisionListDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1DivisionsDivisionListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1DivisionsDivisionListDto:
        """Test DebituraWebExternalApiContractsV1DivisionsDivisionListDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1DivisionsDivisionListDto`
        """
        model = DebituraWebExternalApiContractsV1DivisionsDivisionListDto()
        if include_optional:
            return DebituraWebExternalApiContractsV1DivisionsDivisionListDto(
                page = debitura_debt_collection.models.debitura/domain/model/base/page_data.Debitura.Domain.Model.Base.PageData(
                    total_results = 56, 
                    page_size = 56, 
                    current_page = 56, 
                    response_count = 56, 
                    total_pages = 56, ),
                divisions = [
                    debitura_debt_collection.models.debitura/web/external_api/contracts/v1/divisions/division_dto.Debitura.Web.ExternalApi.Contracts.V1.Divisions.DivisionDto(
                        id = '', 
                        company_name = '', 
                        registration_number = '', 
                        address = '', 
                        zip_code = '', 
                        state = '', 
                        city = '', 
                        country = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/divisions/division_country_dto.Debitura.Web.ExternalApi.Contracts.V1.Divisions.DivisionCountryDto(
                            id = 56, 
                            name = '', 
                            alpha2 = '', ), 
                        office_email = '', 
                        office_phone = '', 
                        is_archived = True, 
                        created_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return DebituraWebExternalApiContractsV1DivisionsDivisionListDto(
                page = debitura_debt_collection.models.debitura/domain/model/base/page_data.Debitura.Domain.Model.Base.PageData(
                    total_results = 56, 
                    page_size = 56, 
                    current_page = 56, 
                    response_count = 56, 
                    total_pages = 56, ),
        )
        """

    def testDebituraWebExternalApiContractsV1DivisionsDivisionListDto(self):
        """Test DebituraWebExternalApiContractsV1DivisionsDivisionListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
