# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_chats_chat_dto import DebituraWebExternalApiContractsV1ChatsChatDto

class TestDebituraWebExternalApiContractsV1ChatsChatDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1ChatsChatDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1ChatsChatDto:
        """Test DebituraWebExternalApiContractsV1ChatsChatDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1ChatsChatDto`
        """
        model = DebituraWebExternalApiContractsV1ChatsChatDto()
        if include_optional:
            return DebituraWebExternalApiContractsV1ChatsChatDto(
                id = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                role = 0,
                role_label = '',
                message = '',
                is_seen = True,
                user = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/users/user_relation_dto.Debitura.Web.ExternalApi.Contracts.V1.Users.UserRelationDto(
                    id = 56, 
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    first_name = '', 
                    last_name = '', 
                    email = '', )
            )
        else:
            return DebituraWebExternalApiContractsV1ChatsChatDto(
        )
        """

    def testDebituraWebExternalApiContractsV1ChatsChatDto(self):
        """Test DebituraWebExternalApiContractsV1ChatsChatDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
