# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_preview_case_response_api_view_model import DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel

class TestDebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel(unittest.TestCase):
    """DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel:
        """Test DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel`
        """
        model = DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel()
        if include_optional:
            return DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel(
                result = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/preview_result_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.PreviewResultDto(
                    is_eligible = True, 
                    ineligibility_reason = '', 
                    partner_assignment = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/partner_assignment_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.PartnerAssignmentDto(
                        collection_partner_id = '', 
                        partner_name = '', 
                        partner_country = '', ), 
                    required_actions = [
                        debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/required_action_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.RequiredActionDto(
                            type = '', 
                            message = '', 
                            solution_url = '', 
                            is_blocking = True, )
                        ], 
                    jurisdiction = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/jurisdiction_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.JurisdictionDto(
                        id = 56, 
                        name = '', 
                        country_alpha2 = '', 
                        state_alpha2 = '', ), 
                    pricing_preview = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/pricing_preview_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.PricingPreviewDto(
                        base_success_fee_percentage = 1.337, 
                        age_surcharge_percentage = 1.337, 
                        total_success_fee_percentage = 1.337, 
                        currency_code = '', 
                        pricing_source = '', 
                        pricing_source_description = '', ), 
                    requires_kyc_verification = True, 
                    has_kyc_on_file = True, 
                    signing_handoff = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/signing_handoff_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.SigningHandoffDto(
                        combined_signing_url = '', ), )
            )
        else:
            return DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel(
        )
        """

    def testDebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel(self):
        """Test DebituraWebExternalApiContractsV1CasesPreviewCaseResponseApiViewModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
