# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.api.cases_api import CasesApi


class TestCasesApi(unittest.TestCase):
    """CasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CasesApi()

    def tearDown(self) -> None:
        pass

    def test_cases_by_creditor_reference_creditor_reference_get(self) -> None:
        """Test case for cases_by_creditor_reference_creditor_reference_get

        Fetch case by creditor reference
        """
        pass

    def test_cases_case_reference_case_reference_get(self) -> None:
        """Test case for cases_case_reference_case_reference_get

        Fetch case by reference
        """
        pass

    def test_cases_get(self) -> None:
        """Test case for cases_get

        List collection cases
        """
        pass

    def test_cases_id_chats_get(self) -> None:
        """Test case for cases_id_chats_get

        Fetch case chats
        """
        pass

    def test_cases_id_chats_post(self) -> None:
        """Test case for cases_id_chats_post

        Send a chat message
        """
        pass

    def test_cases_id_contract_status_get(self) -> None:
        """Test case for cases_id_contract_status_get

        Get contract signing status for a case
        """
        pass

    def test_cases_id_exclusive_period_get(self) -> None:
        """Test case for cases_id_exclusive_period_get

        Get exclusive collection period chain
        """
        pass

    def test_cases_id_files_get(self) -> None:
        """Test case for cases_id_files_get

        Get case files
        """
        pass

    def test_cases_id_files_post(self) -> None:
        """Test case for cases_id_files_post

        Upload a file to a case
        """
        pass

    def test_cases_id_get(self) -> None:
        """Test case for cases_id_get

        Fetch case by ID
        """
        pass

    def test_cases_id_payments_get(self) -> None:
        """Test case for cases_id_payments_get

        Fetch case payments
        """
        pass

    def test_cases_id_quote_requests_get(self) -> None:
        """Test case for cases_id_quote_requests_get

        List quote requests for a case
        """
        pass

    def test_cases_id_quote_requests_quote_request_id_get(self) -> None:
        """Test case for cases_id_quote_requests_quote_request_id_get

        Get quote request details
        """
        pass

    def test_cases_id_quote_requests_quote_request_id_quotes_get(self) -> None:
        """Test case for cases_id_quote_requests_quote_request_id_quotes_get

        List quotes for a quote request
        """
        pass

    def test_cases_id_quote_requests_quote_request_id_quotes_quote_id_get(self) -> None:
        """Test case for cases_id_quote_requests_quote_request_id_quotes_quote_id_get

        Get quote details
        """
        pass

    def test_cases_id_timeline_get(self) -> None:
        """Test case for cases_id_timeline_get

        Fetch case timeline
        """
        pass

    def test_cases_id_validation_get(self) -> None:
        """Test case for cases_id_validation_get

        Get full validation detail for a case
        """
        pass

    def test_cases_post(self) -> None:
        """Test case for cases_post

        Create collection case
        """
        pass

    def test_cases_preview_post(self) -> None:
        """Test case for cases_preview_post

        Preview case eligibility and requirements
        """
        pass


if __name__ == '__main__':
    unittest.main()
