# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_invoice_list_dto import DebituraWebExternalApiContractsV1CasesInvoiceListDto

class TestDebituraWebExternalApiContractsV1CasesInvoiceListDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1CasesInvoiceListDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1CasesInvoiceListDto:
        """Test DebituraWebExternalApiContractsV1CasesInvoiceListDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1CasesInvoiceListDto`
        """
        model = DebituraWebExternalApiContractsV1CasesInvoiceListDto()
        if include_optional:
            return DebituraWebExternalApiContractsV1CasesInvoiceListDto(
                page = debitura_debt_collection.models.debitura/domain/model/base/page_data.Debitura.Domain.Model.Base.PageData(
                    total_results = 56, 
                    page_size = 56, 
                    current_page = 56, 
                    response_count = 56, 
                    total_pages = 56, ),
                cases = [
                    debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/invoice_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.InvoiceDto(
                        id = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        reference = '', 
                        creditor_reference = '', 
                        creditor_comments = '', 
                        claim_description = '', 
                        gross_amount = 1.337, 
                        remainder = 1.337, 
                        interest_fees = 1.337, 
                        reminder_fees = 1.337, 
                        collection_fees = 1.337, 
                        total_added_fees = 1.337, 
                        currency = '', 
                        is_test_case = True, 
                        lifecycle = '', 
                        due_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_finished = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_collection_started = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        close_code = '', 
                        claim_type = '', 
                        creditor_division_id = '', 
                        debtor = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/debtor_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.DebtorDto(
                            type = 'Company', 
                            name = 'Pacific Trading LLC', 
                            contact_person = 'John Smith', 
                            company_registration_number = '47-1234567', 
                            address = '123 Market Street, Suite 400', 
                            zip_code = '94105', 
                            city = 'San Francisco', 
                            state = 'California', 
                            state_alpha2 = 'CA', 
                            country_alpha2 = 'US', 
                            country = 'United States', 
                            email = 'accounts@pacifictrading.com', 
                            phone = '+1 415 555 0123', ), 
                        collection_partner = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/collection_partner_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.CollectionPartnerDto(
                            name = '', 
                            office_email = '', 
                            office_phone = '', 
                            public_site = '', 
                            survey_cadence_mode = 0, ), 
                        creditor = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/creditor_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.CreditorDto(
                            id = '', 
                            company_name = '', 
                            company_registration_number = '', 
                            office_email = '', 
                            office_phone = '', 
                            address = '', 
                            city = '', 
                            zip_code = '', 
                            state = '', 
                            country = '', 
                            division = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/creditor_division_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.CreditorDivisionDto(
                                id = '', 
                                name = '', ), ), 
                        bank_account = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/bank_account_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.BankAccountDto(
                            id = 56, 
                            label = '', 
                            scheme = '', 
                            currency_code = '', 
                            bank_country_code = '', 
                            account_holder_name = '', 
                            iban = '', 
                            bic = '', 
                            account_number = '', 
                            local_identifier = '', 
                            local_identifier_type = '', 
                            bank_name = '', 
                            bank_address = '', 
                            bank_city = '', 
                            bank_zip_code = '', 
                            bank_state = '', ), 
                        blended_age_uplift_points = 1.337, 
                        pre_legal_success_fee = 1.337, 
                        solution_url = '', 
                        signing_handoff = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/signing_handoff_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.SigningHandoffDto(
                            combined_signing_url = '', ), 
                        exclusive_period_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        dispute_status = '', 
                        validation = debitura_debt_collection.models.debitura/domain/services/case_validation/case_validation_lean_dto.Debitura.Domain.Services.CaseValidation.CaseValidationLeanDto(
                            needs_info = True, ), 
                        assigned_user = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/assigned_user_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.AssignedUserDto(
                            email = '', 
                            name = '', ), )
                    ]
            )
        else:
            return DebituraWebExternalApiContractsV1CasesInvoiceListDto(
                page = debitura_debt_collection.models.debitura/domain/model/base/page_data.Debitura.Domain.Model.Base.PageData(
                    total_results = 56, 
                    page_size = 56, 
                    current_page = 56, 
                    response_count = 56, 
                    total_pages = 56, ),
        )
        """

    def testDebituraWebExternalApiContractsV1CasesInvoiceListDto(self):
        """Test DebituraWebExternalApiContractsV1CasesInvoiceListDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
