# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_errors_api_error_response_dto import DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto

class TestDebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto:
        """Test DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto`
        """
        model = DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto()
        if include_optional:
            return DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto(
                error = '',
                message = '',
                business_errors = [
                    debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/business_error_api_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.BusinessErrorApiDTO(
                        type = '', 
                        message = '', 
                        solution_url = '', )
                    ]
            )
        else:
            return DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto(
        )
        """

    def testDebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto(self):
        """Test DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
