# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_leads_lead_dto import DebituraWebExternalApiContractsV1LeadsLeadDto

class TestDebituraWebExternalApiContractsV1LeadsLeadDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1LeadsLeadDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1LeadsLeadDto:
        """Test DebituraWebExternalApiContractsV1LeadsLeadDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1LeadsLeadDto`
        """
        model = DebituraWebExternalApiContractsV1LeadsLeadDto()
        if include_optional:
            return DebituraWebExternalApiContractsV1LeadsLeadDto(
                quote_request_id = '',
                case_id = '',
                status = '',
                lead_flow_status = '',
                quote_type = '',
                max_quotes = 56,
                current_quotes_count = 56,
                outcome = '',
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_qualified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                leads_done_offered = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_reminder_sent = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_reminder_two_sent = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_outcome_selected = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DebituraWebExternalApiContractsV1LeadsLeadDto(
                status = '',
                lead_flow_status = '',
                quote_type = '',
        )
        """

    def testDebituraWebExternalApiContractsV1LeadsLeadDto(self):
        """Test DebituraWebExternalApiContractsV1LeadsLeadDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
