# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_customer_api_models_coverages_case_eligibility_response_api_dto import DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO

class TestDebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO(unittest.TestCase):
    """DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO:
        """Test DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO`
        """
        model = DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO()
        if include_optional:
            return DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO(
                is_eligible = True,
                jurisdiction = debitura_debt_collection.models.debitura/web/external_customer_api/models/coverages/jurisdiction_info_api_dto.Debitura.Web.ExternalCustomerAPI.Models.Coverages.JurisdictionInfoApiDTO(
                    id = 56, 
                    name = '', 
                    country = '', 
                    country_alpha2 = '', 
                    us_state_alpha2 = '', ),
                partner = debitura_debt_collection.models.debitura/web/external_customer_api/models/coverages/partner_info_api_dto.Debitura.Web.ExternalCustomerAPI.Models.Coverages.PartnerInfoApiDTO(
                    id = '', 
                    name = '', ),
                power_of_attorney_status = debitura_debt_collection.models.debitura/web/external_customer_api/models/coverages/power_of_attorney_status_api_dto.Debitura.Web.ExternalCustomerAPI.Models.Coverages.PowerOfAttorneyStatusApiDTO(
                    signed = True, 
                    requires_resigning = True, 
                    invalidation_reason = '', 
                    terms_url = '', 
                    solution_url = '', ),
                error_message = ''
            )
        else:
            return DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO(
        )
        """

    def testDebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO(self):
        """Test DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
