# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_case_timeline_response import DebituraWebExternalApiContractsV1CasesCaseTimelineResponse

class TestDebituraWebExternalApiContractsV1CasesCaseTimelineResponse(unittest.TestCase):
    """DebituraWebExternalApiContractsV1CasesCaseTimelineResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebituraWebExternalApiContractsV1CasesCaseTimelineResponse:
        """Test DebituraWebExternalApiContractsV1CasesCaseTimelineResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebituraWebExternalApiContractsV1CasesCaseTimelineResponse`
        """
        model = DebituraWebExternalApiContractsV1CasesCaseTimelineResponse()
        if include_optional:
            return DebituraWebExternalApiContractsV1CasesCaseTimelineResponse(
                items = [
                    debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/timeline_item_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.TimelineItemDto(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        type = '', 
                        title = '', 
                        description = '', 
                        actor = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/timeline_actor_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.TimelineActorDto(
                            type = '', 
                            name = '', ), )
                    ],
                current_engagement_phase = ''
            )
        else:
            return DebituraWebExternalApiContractsV1CasesCaseTimelineResponse(
                items = [
                    debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/timeline_item_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.TimelineItemDto(
                        date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        type = '', 
                        title = '', 
                        description = '', 
                        actor = debitura_debt_collection.models.debitura/web/external_api/contracts/v1/cases/timeline_actor_dto.Debitura.Web.ExternalApi.Contracts.V1.Cases.TimelineActorDto(
                            type = '', 
                            name = '', ), )
                    ],
        )
        """

    def testDebituraWebExternalApiContractsV1CasesCaseTimelineResponse(self):
        """Test DebituraWebExternalApiContractsV1CasesCaseTimelineResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
