# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_survey_cadence_mode_dto import DebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto

class TestDebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto(unittest.TestCase):
    """DebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto(self):
        """Test DebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto"""
        # inst = DebituraWebExternalApiContractsV1CasesSurveyCadenceModeDto()

if __name__ == '__main__':
    unittest.main()
