# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesJurisdictionDto(BaseModel):
    """
    Geographic jurisdiction information for the case.
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Internal jurisdiction identifier.")
    name: Optional[StrictStr] = Field(default=None, description="Display name of the jurisdiction (e.g., \"Denmark\", \"United States - California\").")
    country_alpha2: Optional[StrictStr] = Field(default=None, description="ISO 3166-1 alpha-2 country code.", alias="countryAlpha2")
    state_alpha2: Optional[StrictStr] = Field(default=None, description="ISO 3166-2 state/region code (only for countries with state-level routing like the US).", alias="stateAlpha2")
    __properties: ClassVar[List[str]] = ["id", "name", "countryAlpha2", "stateAlpha2"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesJurisdictionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if country_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.country_alpha2 is None and "country_alpha2" in self.model_fields_set:
            _dict['countryAlpha2'] = None

        # set to None if state_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.state_alpha2 is None and "state_alpha2" in self.model_fields_set:
            _dict['stateAlpha2'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesJurisdictionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "countryAlpha2": obj.get("countryAlpha2"),
            "stateAlpha2": obj.get("stateAlpha2")
        })
        return _obj


