# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesDebtorDto(BaseModel):
    """
    V1 Debtor DTO for external partner APIs. The debtor is the party that owes the debt.
    """ # noqa: E501
    type: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Debtor type. Valid values: \"Company\" or \"Person\"")
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Debtor name (company name or person's full name)")
    contact_person: Optional[StrictStr] = Field(default=None, description="Contact person at the company (required for companies, not used for persons)", alias="contactPerson")
    company_registration_number: Optional[StrictStr] = Field(default=None, description="Company registration number (VAT number, CVR, org number, etc.)", alias="companyRegistrationNumber")
    address: Optional[StrictStr] = Field(default=None, description="Street address")
    zip_code: Optional[StrictStr] = Field(default=None, description="Postal/ZIP code", alias="zipCode")
    city: Optional[StrictStr] = Field(default=None, description="City name")
    state: Optional[StrictStr] = Field(default=None, description="State/region/province name")
    state_alpha2: Optional[StrictStr] = Field(default=None, description="US state: two-letter code (e.g., \"CA\"), ISO 3166-2 format (e.g., \"US-CA\"), or full name (e.g., \"California\")", alias="stateAlpha2")
    country_alpha2: Optional[StrictStr] = Field(default=None, description="Country code (ISO 3166-1 alpha-2 format)", alias="countryAlpha2")
    country: Optional[StrictStr] = Field(default=None, description="Country name")
    email: Optional[StrictStr] = Field(default=None, description="Email address for debtor contact")
    phone: Optional[StrictStr] = Field(default=None, description="Phone number (include country code)")
    __properties: ClassVar[List[str]] = ["type", "name", "contactPerson", "companyRegistrationNumber", "address", "zipCode", "city", "state", "stateAlpha2", "countryAlpha2", "country", "email", "phone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesDebtorDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if contact_person (nullable) is None
        # and model_fields_set contains the field
        if self.contact_person is None and "contact_person" in self.model_fields_set:
            _dict['contactPerson'] = None

        # set to None if company_registration_number (nullable) is None
        # and model_fields_set contains the field
        if self.company_registration_number is None and "company_registration_number" in self.model_fields_set:
            _dict['companyRegistrationNumber'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.zip_code is None and "zip_code" in self.model_fields_set:
            _dict['zipCode'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if state_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.state_alpha2 is None and "state_alpha2" in self.model_fields_set:
            _dict['stateAlpha2'] = None

        # set to None if country_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.country_alpha2 is None and "country_alpha2" in self.model_fields_set:
            _dict['countryAlpha2'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesDebtorDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "name": obj.get("name"),
            "contactPerson": obj.get("contactPerson"),
            "companyRegistrationNumber": obj.get("companyRegistrationNumber"),
            "address": obj.get("address"),
            "zipCode": obj.get("zipCode"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "stateAlpha2": obj.get("stateAlpha2"),
            "countryAlpha2": obj.get("countryAlpha2"),
            "country": obj.get("country"),
            "email": obj.get("email"),
            "phone": obj.get("phone")
        })
        return _obj


