# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from debitura_debt_collection.models.debitura_web_external_customer_api_models_coverages_partner_coverage_api_dto import DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO(BaseModel):
    """
    Coverage information for a single jurisdiction. BREAKING CHANGE: Partners is now an array - may contain multiple partners with different conditions.
    """ # noqa: E501
    jurisdiction: Optional[StrictStr] = None
    jurisdiction_id: Optional[StrictInt] = Field(default=None, alias="jurisdictionId")
    country: Optional[StrictStr] = None
    country_id: Optional[StrictInt] = Field(default=None, alias="countryId")
    country_alpha2: Optional[StrictStr] = Field(default=None, alias="countryAlpha2")
    us_state_alpha2: Optional[StrictStr] = Field(default=None, alias="usStateAlpha2")
    partners: Optional[List[DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO]] = Field(default=None, description="Collection partners available for this jurisdiction. May be empty if no partners are assigned. May contain multiple partners if different conditions apply (e.g., B2B vs B2C).")
    __properties: ClassVar[List[str]] = ["jurisdiction", "jurisdictionId", "country", "countryId", "countryAlpha2", "usStateAlpha2", "partners"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in partners (list)
        _items = []
        if self.partners:
            for _item in self.partners:
                if _item:
                    _items.append(_item.to_dict())
            _dict['partners'] = _items
        # set to None if jurisdiction (nullable) is None
        # and model_fields_set contains the field
        if self.jurisdiction is None and "jurisdiction" in self.model_fields_set:
            _dict['jurisdiction'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if country_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.country_alpha2 is None and "country_alpha2" in self.model_fields_set:
            _dict['countryAlpha2'] = None

        # set to None if us_state_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.us_state_alpha2 is None and "us_state_alpha2" in self.model_fields_set:
            _dict['usStateAlpha2'] = None

        # set to None if partners (nullable) is None
        # and model_fields_set contains the field
        if self.partners is None and "partners" in self.model_fields_set:
            _dict['partners'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jurisdiction": obj.get("jurisdiction"),
            "jurisdictionId": obj.get("jurisdictionId"),
            "country": obj.get("country"),
            "countryId": obj.get("countryId"),
            "countryAlpha2": obj.get("countryAlpha2"),
            "usStateAlpha2": obj.get("usStateAlpha2"),
            "partners": [DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO.from_dict(_item) for _item in obj["partners"]] if obj.get("partners") is not None else None
        })
        return _obj


