# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1LeadsLeadDto(BaseModel):
    """
    V1 Lead DTO for external customer APIs (summary view)
    """ # noqa: E501
    quote_request_id: Optional[StrictStr] = Field(default=None, alias="quoteRequestId")
    case_id: Optional[StrictStr] = Field(default=None, alias="caseId")
    status: Optional[StrictStr]
    lead_flow_status: Optional[StrictStr] = Field(alias="leadFlowStatus")
    quote_type: Optional[StrictStr] = Field(alias="quoteType")
    max_quotes: Optional[StrictInt] = Field(default=None, alias="maxQuotes")
    current_quotes_count: Optional[StrictInt] = Field(default=None, alias="currentQuotesCount")
    outcome: Optional[StrictStr] = None
    date_created: Optional[datetime] = Field(default=None, alias="dateCreated")
    date_qualified: Optional[datetime] = Field(default=None, alias="dateQualified")
    leads_done_offered: Optional[datetime] = Field(default=None, alias="leadsDoneOffered")
    date_reminder_sent: Optional[datetime] = Field(default=None, alias="dateReminderSent")
    date_reminder_two_sent: Optional[datetime] = Field(default=None, alias="dateReminderTwoSent")
    date_outcome_selected: Optional[datetime] = Field(default=None, alias="dateOutcomeSelected")
    __properties: ClassVar[List[str]] = ["quoteRequestId", "caseId", "status", "leadFlowStatus", "quoteType", "maxQuotes", "currentQuotesCount", "outcome", "dateCreated", "dateQualified", "leadsDoneOffered", "dateReminderSent", "dateReminderTwoSent", "dateOutcomeSelected"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1LeadsLeadDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if lead_flow_status (nullable) is None
        # and model_fields_set contains the field
        if self.lead_flow_status is None and "lead_flow_status" in self.model_fields_set:
            _dict['leadFlowStatus'] = None

        # set to None if quote_type (nullable) is None
        # and model_fields_set contains the field
        if self.quote_type is None and "quote_type" in self.model_fields_set:
            _dict['quoteType'] = None

        # set to None if outcome (nullable) is None
        # and model_fields_set contains the field
        if self.outcome is None and "outcome" in self.model_fields_set:
            _dict['outcome'] = None

        # set to None if date_qualified (nullable) is None
        # and model_fields_set contains the field
        if self.date_qualified is None and "date_qualified" in self.model_fields_set:
            _dict['dateQualified'] = None

        # set to None if leads_done_offered (nullable) is None
        # and model_fields_set contains the field
        if self.leads_done_offered is None and "leads_done_offered" in self.model_fields_set:
            _dict['leadsDoneOffered'] = None

        # set to None if date_reminder_sent (nullable) is None
        # and model_fields_set contains the field
        if self.date_reminder_sent is None and "date_reminder_sent" in self.model_fields_set:
            _dict['dateReminderSent'] = None

        # set to None if date_reminder_two_sent (nullable) is None
        # and model_fields_set contains the field
        if self.date_reminder_two_sent is None and "date_reminder_two_sent" in self.model_fields_set:
            _dict['dateReminderTwoSent'] = None

        # set to None if date_outcome_selected (nullable) is None
        # and model_fields_set contains the field
        if self.date_outcome_selected is None and "date_outcome_selected" in self.model_fields_set:
            _dict['dateOutcomeSelected'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1LeadsLeadDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quoteRequestId": obj.get("quoteRequestId"),
            "caseId": obj.get("caseId"),
            "status": obj.get("status"),
            "leadFlowStatus": obj.get("leadFlowStatus"),
            "quoteType": obj.get("quoteType"),
            "maxQuotes": obj.get("maxQuotes"),
            "currentQuotesCount": obj.get("currentQuotesCount"),
            "outcome": obj.get("outcome"),
            "dateCreated": obj.get("dateCreated"),
            "dateQualified": obj.get("dateQualified"),
            "leadsDoneOffered": obj.get("leadsDoneOffered"),
            "dateReminderSent": obj.get("dateReminderSent"),
            "dateReminderTwoSent": obj.get("dateReminderTwoSent"),
            "dateOutcomeSelected": obj.get("dateOutcomeSelected")
        })
        return _obj


