# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesRequiredActionDto(BaseModel):
    """
    An action required before the case can be submitted (e.g., signing a contract).
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="The type of action required. Common values: \"MissingDebtCollectionContract\", \"MissingPowerOfAttorney\"")
    message: Optional[StrictStr] = Field(default=None, description="Human-readable description of what is required.")
    solution_url: Optional[StrictStr] = Field(default=None, description="URL where the user can complete this <i>specific</i> action (e.g., contract signing page). The URL is context-aware: referral partner tokens get referral onboarding URLs, regular API keys get standard creditor app URLs.               Partners who want a <b>single URL</b> that walks the user through every pending action in one chain — instead of forwarding one URL per `RequiredActionDto` — should use Debitura.Web.ExternalApi.Contracts.V1.Cases.PreviewResultDto.SigningHandoff's `CombinedSigningUrl`. The two are complementary: `SolutionUrl` is granular per-action; `CombinedSigningUrl` is the chain-walking alternative for signing-related actions.", alias="solutionUrl")
    is_blocking: Optional[StrictBool] = Field(default=None, description="Whether this action must be completed before case submission. Currently all returned actions are blocking (true).", alias="isBlocking")
    __properties: ClassVar[List[str]] = ["type", "message", "solutionUrl", "isBlocking"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesRequiredActionDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if solution_url (nullable) is None
        # and model_fields_set contains the field
        if self.solution_url is None and "solution_url" in self.model_fields_set:
            _dict['solutionUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesRequiredActionDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "message": obj.get("message"),
            "solutionUrl": obj.get("solutionUrl"),
            "isBlocking": obj.get("isBlocking")
        })
        return _obj


