# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO(BaseModel):
    """
    Partner coverage details including conditions and PoA status.
    """ # noqa: E501
    partner_id: Optional[StrictStr] = Field(default=None, alias="partnerId")
    partner_name: Optional[StrictStr] = Field(default=None, alias="partnerName")
    conditions: Optional[StrictStr] = Field(default=None, description="Human-readable description of when this partner applies. Examples: \"All cases\", \"B2B cases only\", \"B2C cases ≥ €1000\"")
    signed: Optional[StrictBool] = Field(default=None, description="Whether Power of Attorney has been signed for this partner")
    terms_url: Optional[StrictStr] = Field(default=None, description="URL to download signed PoA document (null if not signed)", alias="termsUrl")
    solution_url: Optional[StrictStr] = Field(default=None, description="URL to sign or re-sign PoA (null if fully signed and valid)", alias="solutionUrl")
    requires_resigning: Optional[StrictBool] = Field(default=None, description="Whether PoA needs to be re-signed (new version available)", alias="requiresResigning")
    invalidation_reason: Optional[StrictStr] = Field(default=None, description="Why re-signing is required (if applicable)", alias="invalidationReason")
    __properties: ClassVar[List[str]] = ["partnerId", "partnerName", "conditions", "signed", "termsUrl", "solutionUrl", "requiresResigning", "invalidationReason"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if partner_name (nullable) is None
        # and model_fields_set contains the field
        if self.partner_name is None and "partner_name" in self.model_fields_set:
            _dict['partnerName'] = None

        # set to None if conditions (nullable) is None
        # and model_fields_set contains the field
        if self.conditions is None and "conditions" in self.model_fields_set:
            _dict['conditions'] = None

        # set to None if terms_url (nullable) is None
        # and model_fields_set contains the field
        if self.terms_url is None and "terms_url" in self.model_fields_set:
            _dict['termsUrl'] = None

        # set to None if solution_url (nullable) is None
        # and model_fields_set contains the field
        if self.solution_url is None and "solution_url" in self.model_fields_set:
            _dict['solutionUrl'] = None

        # set to None if invalidation_reason (nullable) is None
        # and model_fields_set contains the field
        if self.invalidation_reason is None and "invalidation_reason" in self.model_fields_set:
            _dict['invalidationReason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesPartnerCoverageApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "partnerId": obj.get("partnerId"),
            "partnerName": obj.get("partnerName"),
            "conditions": obj.get("conditions"),
            "signed": obj.get("signed"),
            "termsUrl": obj.get("termsUrl"),
            "solutionUrl": obj.get("solutionUrl"),
            "requiresResigning": obj.get("requiresResigning"),
            "invalidationReason": obj.get("invalidationReason")
        })
        return _obj


