# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DebituraDomainModelCommunicationCenterChatsChatRole(int, Enum):
    """
    DebituraDomainModelCommunicationCenterChatsChatRole
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1 = 1
    NUMBER_2 = 2

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DebituraDomainModelCommunicationCenterChatsChatRole from a JSON string"""
        return cls(json.loads(json_str))


