# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from debitura_debt_collection.models.debitura_domain_services_case_validation_case_validation_lean_dto import DebituraDomainServicesCaseValidationCaseValidationLeanDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_assigned_user_dto import DebituraWebExternalApiContractsV1CasesAssignedUserDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_bank_account_dto import DebituraWebExternalApiContractsV1CasesBankAccountDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_collection_partner_dto import DebituraWebExternalApiContractsV1CasesCollectionPartnerDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_creditor_dto import DebituraWebExternalApiContractsV1CasesCreditorDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_debtor_dto import DebituraWebExternalApiContractsV1CasesDebtorDto
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_signing_handoff_dto import DebituraWebExternalApiContractsV1CasesSigningHandoffDto
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesInvoiceDto(BaseModel):
    """
    V1 Invoice DTO for external partner APIs
    """ # noqa: E501
    id: Optional[StrictStr] = None
    date_created: Optional[datetime] = Field(default=None, alias="dateCreated")
    date_updated: Optional[datetime] = Field(default=None, alias="dateUpdated")
    reference: Optional[StrictStr] = None
    creditor_reference: Optional[StrictStr] = Field(default=None, alias="creditorReference")
    creditor_comments: Optional[StrictStr] = Field(default=None, alias="creditorComments")
    claim_description: Optional[StrictStr] = Field(default=None, alias="claimDescription")
    gross_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="grossAmount")
    remainder: Optional[Union[StrictFloat, StrictInt]] = None
    interest_fees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="interestFees")
    reminder_fees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="reminderFees")
    collection_fees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="collectionFees")
    total_added_fees: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="totalAddedFees")
    currency: Optional[StrictStr] = None
    is_test_case: Optional[StrictBool] = Field(default=None, alias="isTestCase")
    lifecycle: Optional[StrictStr] = None
    due_date: Optional[datetime] = Field(default=None, alias="dueDate")
    var_date: Optional[datetime] = Field(default=None, alias="date")
    date_finished: Optional[datetime] = Field(default=None, alias="dateFinished")
    date_collection_started: Optional[datetime] = Field(default=None, alias="dateCollectionStarted")
    close_code: Optional[StrictStr] = Field(default=None, alias="closeCode")
    claim_type: Optional[StrictStr] = Field(default=None, description="The type of claim for this case (e.g. \"Unpaid Invoice\", \"Loan Repayment\", \"Breach of Contract\"). Null if not set.", alias="claimType")
    creditor_division_id: Optional[StrictStr] = Field(default=None, alias="creditorDivisionId")
    debtor: Optional[DebituraWebExternalApiContractsV1CasesDebtorDto] = None
    collection_partner: Optional[DebituraWebExternalApiContractsV1CasesCollectionPartnerDto] = Field(default=None, alias="collectionPartner")
    creditor: Optional[DebituraWebExternalApiContractsV1CasesCreditorDto] = None
    bank_account: Optional[DebituraWebExternalApiContractsV1CasesBankAccountDto] = Field(default=None, alias="bankAccount")
    blended_age_uplift_points: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="MULTI-INVOICE AGE BUCKET PRICING Calculated blended age uplift percentage points (0-20) for multi-invoice cases. Shows the additional fee percentage added due to invoice age. Formula: ((A12-A24)×10 + A24×20) / Total Principal Null for single-invoice cases (age uplift is calculated from due date instead).", alias="blendedAgeUpliftPoints")
    pre_legal_success_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="PRE-LEGAL SUCCESS FEE The total pre-legal success fee percentage for this case. Includes base fee + age-based uplift (blended or single-invoice). Null if pricing has not been calculated yet or if case is not in pre-legal phase. Example: 20.5 represents 20.5% success fee.", alias="preLegalSuccessFee")
    solution_url: Optional[StrictStr] = Field(default=None, description="When the case is created with allowPendingContracts=true and required contracts are unsigned, this URL points to the signing page. Null when contracts are already signed or not applicable.", alias="solutionUrl")
    signing_handoff: Optional[DebituraWebExternalApiContractsV1CasesSigningHandoffDto] = Field(default=None, alias="signingHandoff")
    exclusive_period_end_date: Optional[datetime] = Field(default=None, description="The date the exclusive collection period ends (or ended). Null if no collection period has been created for this case (e.g. custom-terms cases). Use GET /cases/{id}/exclusive-period for the full chain including extensions.", alias="exclusivePeriodEndDate")
    dispute_status: Optional[StrictStr] = Field(default=None, description="Whether the claim is disputed by the debtor. Returns the description of Debitura.Domain.Model.Receiveables.Invoices.Enums.ClaimDisputeStatus: \"Yes, the claim is disputed\", \"No, the claim is not disputed\", or \"Don't Know\". Null when the dispute status has not been set on the case.", alias="disputeStatus")
    validation: Optional[DebituraDomainServicesCaseValidationCaseValidationLeanDto] = None
    assigned_user: Optional[DebituraWebExternalApiContractsV1CasesAssignedUserDto] = Field(default=None, alias="assignedUser")
    __properties: ClassVar[List[str]] = ["id", "dateCreated", "dateUpdated", "reference", "creditorReference", "creditorComments", "claimDescription", "grossAmount", "remainder", "interestFees", "reminderFees", "collectionFees", "totalAddedFees", "currency", "isTestCase", "lifecycle", "dueDate", "date", "dateFinished", "dateCollectionStarted", "closeCode", "claimType", "creditorDivisionId", "debtor", "collectionPartner", "creditor", "bankAccount", "blendedAgeUpliftPoints", "preLegalSuccessFee", "solutionUrl", "signingHandoff", "exclusivePeriodEndDate", "disputeStatus", "validation", "assignedUser"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesInvoiceDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of debtor
        if self.debtor:
            _dict['debtor'] = self.debtor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of collection_partner
        if self.collection_partner:
            _dict['collectionPartner'] = self.collection_partner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of creditor
        if self.creditor:
            _dict['creditor'] = self.creditor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bank_account
        if self.bank_account:
            _dict['bankAccount'] = self.bank_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of signing_handoff
        if self.signing_handoff:
            _dict['signingHandoff'] = self.signing_handoff.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validation
        if self.validation:
            _dict['validation'] = self.validation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of assigned_user
        if self.assigned_user:
            _dict['assignedUser'] = self.assigned_user.to_dict()
        # set to None if date_updated (nullable) is None
        # and model_fields_set contains the field
        if self.date_updated is None and "date_updated" in self.model_fields_set:
            _dict['dateUpdated'] = None

        # set to None if reference (nullable) is None
        # and model_fields_set contains the field
        if self.reference is None and "reference" in self.model_fields_set:
            _dict['reference'] = None

        # set to None if creditor_reference (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_reference is None and "creditor_reference" in self.model_fields_set:
            _dict['creditorReference'] = None

        # set to None if creditor_comments (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_comments is None and "creditor_comments" in self.model_fields_set:
            _dict['creditorComments'] = None

        # set to None if claim_description (nullable) is None
        # and model_fields_set contains the field
        if self.claim_description is None and "claim_description" in self.model_fields_set:
            _dict['claimDescription'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if lifecycle (nullable) is None
        # and model_fields_set contains the field
        if self.lifecycle is None and "lifecycle" in self.model_fields_set:
            _dict['lifecycle'] = None

        # set to None if date_finished (nullable) is None
        # and model_fields_set contains the field
        if self.date_finished is None and "date_finished" in self.model_fields_set:
            _dict['dateFinished'] = None

        # set to None if date_collection_started (nullable) is None
        # and model_fields_set contains the field
        if self.date_collection_started is None and "date_collection_started" in self.model_fields_set:
            _dict['dateCollectionStarted'] = None

        # set to None if close_code (nullable) is None
        # and model_fields_set contains the field
        if self.close_code is None and "close_code" in self.model_fields_set:
            _dict['closeCode'] = None

        # set to None if claim_type (nullable) is None
        # and model_fields_set contains the field
        if self.claim_type is None and "claim_type" in self.model_fields_set:
            _dict['claimType'] = None

        # set to None if creditor_division_id (nullable) is None
        # and model_fields_set contains the field
        if self.creditor_division_id is None and "creditor_division_id" in self.model_fields_set:
            _dict['creditorDivisionId'] = None

        # set to None if blended_age_uplift_points (nullable) is None
        # and model_fields_set contains the field
        if self.blended_age_uplift_points is None and "blended_age_uplift_points" in self.model_fields_set:
            _dict['blendedAgeUpliftPoints'] = None

        # set to None if pre_legal_success_fee (nullable) is None
        # and model_fields_set contains the field
        if self.pre_legal_success_fee is None and "pre_legal_success_fee" in self.model_fields_set:
            _dict['preLegalSuccessFee'] = None

        # set to None if solution_url (nullable) is None
        # and model_fields_set contains the field
        if self.solution_url is None and "solution_url" in self.model_fields_set:
            _dict['solutionUrl'] = None

        # set to None if exclusive_period_end_date (nullable) is None
        # and model_fields_set contains the field
        if self.exclusive_period_end_date is None and "exclusive_period_end_date" in self.model_fields_set:
            _dict['exclusivePeriodEndDate'] = None

        # set to None if dispute_status (nullable) is None
        # and model_fields_set contains the field
        if self.dispute_status is None and "dispute_status" in self.model_fields_set:
            _dict['disputeStatus'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesInvoiceDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dateCreated": obj.get("dateCreated"),
            "dateUpdated": obj.get("dateUpdated"),
            "reference": obj.get("reference"),
            "creditorReference": obj.get("creditorReference"),
            "creditorComments": obj.get("creditorComments"),
            "claimDescription": obj.get("claimDescription"),
            "grossAmount": obj.get("grossAmount"),
            "remainder": obj.get("remainder"),
            "interestFees": obj.get("interestFees"),
            "reminderFees": obj.get("reminderFees"),
            "collectionFees": obj.get("collectionFees"),
            "totalAddedFees": obj.get("totalAddedFees"),
            "currency": obj.get("currency"),
            "isTestCase": obj.get("isTestCase"),
            "lifecycle": obj.get("lifecycle"),
            "dueDate": obj.get("dueDate"),
            "date": obj.get("date"),
            "dateFinished": obj.get("dateFinished"),
            "dateCollectionStarted": obj.get("dateCollectionStarted"),
            "closeCode": obj.get("closeCode"),
            "claimType": obj.get("claimType"),
            "creditorDivisionId": obj.get("creditorDivisionId"),
            "debtor": DebituraWebExternalApiContractsV1CasesDebtorDto.from_dict(obj["debtor"]) if obj.get("debtor") is not None else None,
            "collectionPartner": DebituraWebExternalApiContractsV1CasesCollectionPartnerDto.from_dict(obj["collectionPartner"]) if obj.get("collectionPartner") is not None else None,
            "creditor": DebituraWebExternalApiContractsV1CasesCreditorDto.from_dict(obj["creditor"]) if obj.get("creditor") is not None else None,
            "bankAccount": DebituraWebExternalApiContractsV1CasesBankAccountDto.from_dict(obj["bankAccount"]) if obj.get("bankAccount") is not None else None,
            "blendedAgeUpliftPoints": obj.get("blendedAgeUpliftPoints"),
            "preLegalSuccessFee": obj.get("preLegalSuccessFee"),
            "solutionUrl": obj.get("solutionUrl"),
            "signingHandoff": DebituraWebExternalApiContractsV1CasesSigningHandoffDto.from_dict(obj["signingHandoff"]) if obj.get("signingHandoff") is not None else None,
            "exclusivePeriodEndDate": obj.get("exclusivePeriodEndDate"),
            "disputeStatus": obj.get("disputeStatus"),
            "validation": DebituraDomainServicesCaseValidationCaseValidationLeanDto.from_dict(obj["validation"]) if obj.get("validation") is not None else None,
            "assignedUser": DebituraWebExternalApiContractsV1CasesAssignedUserDto.from_dict(obj["assignedUser"]) if obj.get("assignedUser") is not None else None
        })
        return _obj


