# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from debitura_debt_collection.models.debitura_domain_model_communication_center_chats_chat_role import DebituraDomainModelCommunicationCenterChatsChatRole
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_users_user_relation_dto import DebituraWebExternalApiContractsV1UsersUserRelationDto
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1ChatsChatDto(BaseModel):
    """
    DebituraWebExternalApiContractsV1ChatsChatDto
    """ # noqa: E501
    id: Optional[StrictStr] = None
    date_created: Optional[datetime] = Field(default=None, alias="dateCreated")
    date_updated: Optional[datetime] = Field(default=None, alias="dateUpdated")
    role: Optional[DebituraDomainModelCommunicationCenterChatsChatRole] = None
    role_label: Optional[StrictStr] = Field(default=None, description="Human-readable label for the role (e.g., \"Partner\", \"Creditor\", \"Managed by partner\"). Companion to Debitura.Web.ExternalApi.Contracts.V1.Chats.ChatDto.Role — always present when Role is set.", alias="roleLabel")
    message: Optional[StrictStr] = None
    is_seen: Optional[StrictBool] = Field(default=None, alias="isSeen")
    user: Optional[DebituraWebExternalApiContractsV1UsersUserRelationDto] = None
    __properties: ClassVar[List[str]] = ["id", "dateCreated", "dateUpdated", "role", "roleLabel", "message", "isSeen", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1ChatsChatDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # set to None if date_updated (nullable) is None
        # and model_fields_set contains the field
        if self.date_updated is None and "date_updated" in self.model_fields_set:
            _dict['dateUpdated'] = None

        # set to None if role_label (nullable) is None
        # and model_fields_set contains the field
        if self.role_label is None and "role_label" in self.model_fields_set:
            _dict['roleLabel'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1ChatsChatDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dateCreated": obj.get("dateCreated"),
            "dateUpdated": obj.get("dateUpdated"),
            "role": obj.get("role"),
            "roleLabel": obj.get("roleLabel"),
            "message": obj.get("message"),
            "isSeen": obj.get("isSeen"),
            "user": DebituraWebExternalApiContractsV1UsersUserRelationDto.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


