# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1LeadsLeadQuoteDto(BaseModel):
    """
    V1 Lead Quote DTO for external customer APIs (summary view)
    """ # noqa: E501
    quote_id: Optional[StrictStr] = Field(default=None, alias="quoteId")
    quote_request_id: Optional[StrictStr] = Field(default=None, alias="quoteRequestId")
    partner_id: Optional[StrictStr] = Field(default=None, alias="partnerId")
    partner_name: Optional[StrictStr] = Field(alias="partnerName")
    status: Optional[StrictStr]
    agreement_type: Optional[StrictStr] = Field(alias="agreementType")
    hourly_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="hourlyRate")
    hourly_estimated: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="hourlyEstimated")
    flat_fee_estimate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="flatFeeEstimate")
    success_fee: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="successFee")
    hybrid_estimate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="hybridEstimate")
    proposed_solution: Optional[StrictStr] = Field(default=None, alias="proposedSolution")
    partner_why_us_section: Optional[StrictStr] = Field(default=None, alias="partnerWhyUsSection")
    phase: Optional[StrictStr] = Field(default=None, description="The case phase this quote offers to work in (Pre-legal / Legal / Enforcement). Null = unspecified.")
    offer_nature: Optional[StrictStr] = Field(default=None, description="Whether declining stops the case (Recommendation / Required). v1: display only. Null = unspecified.", alias="offerNature")
    currency: Optional[StrictStr]
    date_created: Optional[datetime] = Field(default=None, alias="dateCreated")
    __properties: ClassVar[List[str]] = ["quoteId", "quoteRequestId", "partnerId", "partnerName", "status", "agreementType", "hourlyRate", "hourlyEstimated", "flatFeeEstimate", "successFee", "hybridEstimate", "proposedSolution", "partnerWhyUsSection", "phase", "offerNature", "currency", "dateCreated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1LeadsLeadQuoteDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if partner_name (nullable) is None
        # and model_fields_set contains the field
        if self.partner_name is None and "partner_name" in self.model_fields_set:
            _dict['partnerName'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if agreement_type (nullable) is None
        # and model_fields_set contains the field
        if self.agreement_type is None and "agreement_type" in self.model_fields_set:
            _dict['agreementType'] = None

        # set to None if hourly_rate (nullable) is None
        # and model_fields_set contains the field
        if self.hourly_rate is None and "hourly_rate" in self.model_fields_set:
            _dict['hourlyRate'] = None

        # set to None if hourly_estimated (nullable) is None
        # and model_fields_set contains the field
        if self.hourly_estimated is None and "hourly_estimated" in self.model_fields_set:
            _dict['hourlyEstimated'] = None

        # set to None if flat_fee_estimate (nullable) is None
        # and model_fields_set contains the field
        if self.flat_fee_estimate is None and "flat_fee_estimate" in self.model_fields_set:
            _dict['flatFeeEstimate'] = None

        # set to None if success_fee (nullable) is None
        # and model_fields_set contains the field
        if self.success_fee is None and "success_fee" in self.model_fields_set:
            _dict['successFee'] = None

        # set to None if hybrid_estimate (nullable) is None
        # and model_fields_set contains the field
        if self.hybrid_estimate is None and "hybrid_estimate" in self.model_fields_set:
            _dict['hybridEstimate'] = None

        # set to None if proposed_solution (nullable) is None
        # and model_fields_set contains the field
        if self.proposed_solution is None and "proposed_solution" in self.model_fields_set:
            _dict['proposedSolution'] = None

        # set to None if partner_why_us_section (nullable) is None
        # and model_fields_set contains the field
        if self.partner_why_us_section is None and "partner_why_us_section" in self.model_fields_set:
            _dict['partnerWhyUsSection'] = None

        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if offer_nature (nullable) is None
        # and model_fields_set contains the field
        if self.offer_nature is None and "offer_nature" in self.model_fields_set:
            _dict['offerNature'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1LeadsLeadQuoteDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quoteId": obj.get("quoteId"),
            "quoteRequestId": obj.get("quoteRequestId"),
            "partnerId": obj.get("partnerId"),
            "partnerName": obj.get("partnerName"),
            "status": obj.get("status"),
            "agreementType": obj.get("agreementType"),
            "hourlyRate": obj.get("hourlyRate"),
            "hourlyEstimated": obj.get("hourlyEstimated"),
            "flatFeeEstimate": obj.get("flatFeeEstimate"),
            "successFee": obj.get("successFee"),
            "hybridEstimate": obj.get("hybridEstimate"),
            "proposedSolution": obj.get("proposedSolution"),
            "partnerWhyUsSection": obj.get("partnerWhyUsSection"),
            "phase": obj.get("phase"),
            "offerNature": obj.get("offerNature"),
            "currency": obj.get("currency"),
            "dateCreated": obj.get("dateCreated")
        })
        return _obj


