# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalCustomerAPIModelsWebhooksDtosWebhookEventDto(BaseModel):
    """
    Represents a recorded webhook delivery event.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique identifier for this event record. Use this ID to replay the event via `POST /webhooks/events/{id}/replay`.")
    subscription_id: Optional[StrictStr] = Field(default=None, description="The webhook subscription this event was dispatched to.", alias="subscriptionId")
    case_id: Optional[StrictStr] = Field(default=None, description="The collection case this event relates to.", alias="caseId")
    event_type: Optional[StrictStr] = Field(default=None, description="The event type (e.g. \"case.created\", \"payment.created\").", alias="eventType")
    payload: Optional[StrictStr] = Field(default=None, description="The full JSON payload that was (or will be) delivered.")
    created_at: Optional[datetime] = Field(default=None, description="When this event was first recorded (UTC).", alias="createdAt")
    delivered_at: Optional[datetime] = Field(default=None, description="When the event was successfully delivered (UTC). Null if delivery has not yet succeeded.", alias="deliveredAt")
    attempt_count: Optional[StrictInt] = Field(default=None, description="Number of delivery attempts made so far.", alias="attemptCount")
    last_response_code: Optional[StrictInt] = Field(default=None, description="HTTP status code returned by the subscriber endpoint on the last attempt.", alias="lastResponseCode")
    last_error: Optional[StrictStr] = Field(default=None, description="Error message from the last failed delivery attempt. Null on successful delivery.", alias="lastError")
    __properties: ClassVar[List[str]] = ["id", "subscriptionId", "caseId", "eventType", "payload", "createdAt", "deliveredAt", "attemptCount", "lastResponseCode", "lastError"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsWebhooksDtosWebhookEventDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if case_id (nullable) is None
        # and model_fields_set contains the field
        if self.case_id is None and "case_id" in self.model_fields_set:
            _dict['caseId'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['eventType'] = None

        # set to None if payload (nullable) is None
        # and model_fields_set contains the field
        if self.payload is None and "payload" in self.model_fields_set:
            _dict['payload'] = None

        # set to None if delivered_at (nullable) is None
        # and model_fields_set contains the field
        if self.delivered_at is None and "delivered_at" in self.model_fields_set:
            _dict['deliveredAt'] = None

        # set to None if last_response_code (nullable) is None
        # and model_fields_set contains the field
        if self.last_response_code is None and "last_response_code" in self.model_fields_set:
            _dict['lastResponseCode'] = None

        # set to None if last_error (nullable) is None
        # and model_fields_set contains the field
        if self.last_error is None and "last_error" in self.model_fields_set:
            _dict['lastError'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsWebhooksDtosWebhookEventDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "subscriptionId": obj.get("subscriptionId"),
            "caseId": obj.get("caseId"),
            "eventType": obj.get("eventType"),
            "payload": obj.get("payload"),
            "createdAt": obj.get("createdAt"),
            "deliveredAt": obj.get("deliveredAt"),
            "attemptCount": obj.get("attemptCount"),
            "lastResponseCode": obj.get("lastResponseCode"),
            "lastError": obj.get("lastError")
        })
        return _obj


