# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO(BaseModel):
    """
    Request for checking case eligibility and getting partner/PoA status.
    """ # noqa: E501
    country_alpha2: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Debtor country (2-letter ISO code, e.g., \"DK\", \"US\", \"DE\")", alias="countryAlpha2")
    state_alpha2: Optional[StrictStr] = Field(default=None, description="US state code for US debtors (e.g., \"CA\", \"NY\"). Required if CountryAlpha2 = \"US\"", alias="stateAlpha2")
    debtor_type: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Debtor type: \"Company\" or \"Private\"", alias="debtorType")
    amount: Union[Annotated[float, Field(le=1.7976931348623157E+308, strict=True, ge=0.01)], Annotated[int, Field(le=2147483647, strict=True, ge=1)]] = Field(description="Amount to recover in specified currency")
    currency_code: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Currency code (e.g., \"USD\", \"EUR\", \"DKK\")", alias="currencyCode")
    __properties: ClassVar[List[str]] = ["countryAlpha2", "stateAlpha2", "debtorType", "amount", "currencyCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if state_alpha2 (nullable) is None
        # and model_fields_set contains the field
        if self.state_alpha2 is None and "state_alpha2" in self.model_fields_set:
            _dict['stateAlpha2'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "countryAlpha2": obj.get("countryAlpha2"),
            "stateAlpha2": obj.get("stateAlpha2"),
            "debtorType": obj.get("debtorType"),
            "amount": obj.get("amount"),
            "currencyCode": obj.get("currencyCode")
        })
        return _obj


