# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesBankAccountDto(BaseModel):
    """
    Bank account information for partner API. Full details provided as partners need this to: 1. Provide payment instructions to debtors (when debtor pays client directly) 2. Execute payouts to clients (when partner receives payment and pays out remainder)
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Bank account identifier")
    label: Optional[StrictStr] = Field(default=None, description="User-friendly label (e.g., \"Main EUR Account\")")
    scheme: Optional[StrictStr] = Field(default=None, description="Account scheme: IBAN, SWIFT, or LOCAL")
    currency_code: Optional[StrictStr] = Field(default=None, description="Currency code (ISO 4217)", alias="currencyCode")
    bank_country_code: Optional[StrictStr] = Field(default=None, description="Bank country code (ISO Alpha-2)", alias="bankCountryCode")
    account_holder_name: Optional[StrictStr] = Field(default=None, description="Account holder name (beneficiary)", alias="accountHolderName")
    iban: Optional[StrictStr] = Field(default=None, description="IBAN (for IBAN scheme accounts)")
    bic: Optional[StrictStr] = Field(default=None, description="BIC/SWIFT code (for IBAN and SWIFT scheme accounts)")
    account_number: Optional[StrictStr] = Field(default=None, description="Account number (for SWIFT and LOCAL scheme accounts)", alias="accountNumber")
    local_identifier: Optional[StrictStr] = Field(default=None, description="Local identifier (for LOCAL scheme accounts, e.g., sort code + account number)", alias="localIdentifier")
    local_identifier_type: Optional[StrictStr] = Field(default=None, description="Type of local identifier (e.g., \"Sort Code\", \"Routing Number\")", alias="localIdentifierType")
    bank_name: Optional[StrictStr] = Field(default=None, description="Bank name (optional)", alias="bankName")
    bank_address: Optional[StrictStr] = Field(default=None, description="Bank address (optional)", alias="bankAddress")
    bank_city: Optional[StrictStr] = Field(default=None, description="Bank city (optional)", alias="bankCity")
    bank_zip_code: Optional[StrictStr] = Field(default=None, description="Bank zip/postal code (optional)", alias="bankZipCode")
    bank_state: Optional[StrictStr] = Field(default=None, description="Bank state/region (optional)", alias="bankState")
    __properties: ClassVar[List[str]] = ["id", "label", "scheme", "currencyCode", "bankCountryCode", "accountHolderName", "iban", "bic", "accountNumber", "localIdentifier", "localIdentifierType", "bankName", "bankAddress", "bankCity", "bankZipCode", "bankState"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesBankAccountDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if scheme (nullable) is None
        # and model_fields_set contains the field
        if self.scheme is None and "scheme" in self.model_fields_set:
            _dict['scheme'] = None

        # set to None if currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.currency_code is None and "currency_code" in self.model_fields_set:
            _dict['currencyCode'] = None

        # set to None if bank_country_code (nullable) is None
        # and model_fields_set contains the field
        if self.bank_country_code is None and "bank_country_code" in self.model_fields_set:
            _dict['bankCountryCode'] = None

        # set to None if account_holder_name (nullable) is None
        # and model_fields_set contains the field
        if self.account_holder_name is None and "account_holder_name" in self.model_fields_set:
            _dict['accountHolderName'] = None

        # set to None if iban (nullable) is None
        # and model_fields_set contains the field
        if self.iban is None and "iban" in self.model_fields_set:
            _dict['iban'] = None

        # set to None if bic (nullable) is None
        # and model_fields_set contains the field
        if self.bic is None and "bic" in self.model_fields_set:
            _dict['bic'] = None

        # set to None if account_number (nullable) is None
        # and model_fields_set contains the field
        if self.account_number is None and "account_number" in self.model_fields_set:
            _dict['accountNumber'] = None

        # set to None if local_identifier (nullable) is None
        # and model_fields_set contains the field
        if self.local_identifier is None and "local_identifier" in self.model_fields_set:
            _dict['localIdentifier'] = None

        # set to None if local_identifier_type (nullable) is None
        # and model_fields_set contains the field
        if self.local_identifier_type is None and "local_identifier_type" in self.model_fields_set:
            _dict['localIdentifierType'] = None

        # set to None if bank_name (nullable) is None
        # and model_fields_set contains the field
        if self.bank_name is None and "bank_name" in self.model_fields_set:
            _dict['bankName'] = None

        # set to None if bank_address (nullable) is None
        # and model_fields_set contains the field
        if self.bank_address is None and "bank_address" in self.model_fields_set:
            _dict['bankAddress'] = None

        # set to None if bank_city (nullable) is None
        # and model_fields_set contains the field
        if self.bank_city is None and "bank_city" in self.model_fields_set:
            _dict['bankCity'] = None

        # set to None if bank_zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.bank_zip_code is None and "bank_zip_code" in self.model_fields_set:
            _dict['bankZipCode'] = None

        # set to None if bank_state (nullable) is None
        # and model_fields_set contains the field
        if self.bank_state is None and "bank_state" in self.model_fields_set:
            _dict['bankState'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesBankAccountDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "label": obj.get("label"),
            "scheme": obj.get("scheme"),
            "currencyCode": obj.get("currencyCode"),
            "bankCountryCode": obj.get("bankCountryCode"),
            "accountHolderName": obj.get("accountHolderName"),
            "iban": obj.get("iban"),
            "bic": obj.get("bic"),
            "accountNumber": obj.get("accountNumber"),
            "localIdentifier": obj.get("localIdentifier"),
            "localIdentifierType": obj.get("localIdentifierType"),
            "bankName": obj.get("bankName"),
            "bankAddress": obj.get("bankAddress"),
            "bankCity": obj.get("bankCity"),
            "bankZipCode": obj.get("bankZipCode"),
            "bankState": obj.get("bankState")
        })
        return _obj


