# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from debitura_debt_collection.models.debitura_web_external_customer_api_models_coverages_jurisdiction_info_api_dto import DebituraWebExternalCustomerAPIModelsCoveragesJurisdictionInfoApiDTO
from debitura_debt_collection.models.debitura_web_external_customer_api_models_coverages_partner_info_api_dto import DebituraWebExternalCustomerAPIModelsCoveragesPartnerInfoApiDTO
from debitura_debt_collection.models.debitura_web_external_customer_api_models_coverages_power_of_attorney_status_api_dto import DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO(BaseModel):
    """
    Response for case eligibility check - returns exact partner + PoA status.
    """ # noqa: E501
    is_eligible: Optional[StrictBool] = Field(default=None, description="Whether a collection partner is available for this case", alias="isEligible")
    jurisdiction: Optional[DebituraWebExternalCustomerAPIModelsCoveragesJurisdictionInfoApiDTO] = None
    partner: Optional[DebituraWebExternalCustomerAPIModelsCoveragesPartnerInfoApiDTO] = None
    power_of_attorney_status: Optional[DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO] = Field(default=None, alias="powerOfAttorneyStatus")
    error_message: Optional[StrictStr] = Field(default=None, description="Error message if IsEligible = false. Branch on Debitura.Web.ExternalCustomerAPI.Models.Coverages.CaseEligibilityResponseApiDTO.IneligibilityReasonCode rather than on this text, which may be reworded.", alias="errorMessage")
    ineligibility_reason_code: Optional[StrictStr] = Field(default=None, description="Stable machine-readable reason, present whenever Debitura.Web.ExternalCustomerAPI.Models.Coverages.CaseEligibilityResponseApiDTO.ErrorMessage is. One of: NoGeographicCoverage, AmountBelowMinimum, AmountAboveMaximum, DebtorTypeNotCovered, NotCoveredByPartnerRules, ExcludedForClient, EligibilityUndetermined.  Only NoGeographicCoverage means we have no partner in the jurisdiction. AmountBelowMinimum means the geography IS covered and only the claim amount fell short. EligibilityUndetermined is a transient failure on our side, not a statement about coverage.", alias="ineligibilityReasonCode")
    applicable_minimum_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The lowest claim amount accepted for this jurisdiction and debtor type, in the currency of the request. Present on ELIGIBLE responses too, so the floor can be shown without a second call. Null when no partner covering this case declares a minimum.", alias="applicableMinimumAmount")
    applicable_minimum_currency_code: Optional[StrictStr] = Field(default=None, description="ISO code that Debitura.Web.ExternalCustomerAPI.Models.Coverages.CaseEligibilityResponseApiDTO.ApplicableMinimumAmount is expressed in.", alias="applicableMinimumCurrencyCode")
    amount_check_unavailable: Optional[StrictBool] = Field(default=None, description="True when a currency conversion needed to evaluate the claim amount was unavailable, so the amount-based part of this answer was NOT actually checked It can be true on an eligible answer: a partner matched only because amount conditions failed open while rates were down. Treat such an answer as provisional and retry rather than relying on the floor having been applied.", alias="amountCheckUnavailable")
    __properties: ClassVar[List[str]] = ["isEligible", "jurisdiction", "partner", "powerOfAttorneyStatus", "errorMessage", "ineligibilityReasonCode", "applicableMinimumAmount", "applicableMinimumCurrencyCode", "amountCheckUnavailable"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of jurisdiction
        if self.jurisdiction:
            _dict['jurisdiction'] = self.jurisdiction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of partner
        if self.partner:
            _dict['partner'] = self.partner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of power_of_attorney_status
        if self.power_of_attorney_status:
            _dict['powerOfAttorneyStatus'] = self.power_of_attorney_status.to_dict()
        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if ineligibility_reason_code (nullable) is None
        # and model_fields_set contains the field
        if self.ineligibility_reason_code is None and "ineligibility_reason_code" in self.model_fields_set:
            _dict['ineligibilityReasonCode'] = None

        # set to None if applicable_minimum_amount (nullable) is None
        # and model_fields_set contains the field
        if self.applicable_minimum_amount is None and "applicable_minimum_amount" in self.model_fields_set:
            _dict['applicableMinimumAmount'] = None

        # set to None if applicable_minimum_currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.applicable_minimum_currency_code is None and "applicable_minimum_currency_code" in self.model_fields_set:
            _dict['applicableMinimumCurrencyCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "isEligible": obj.get("isEligible"),
            "jurisdiction": DebituraWebExternalCustomerAPIModelsCoveragesJurisdictionInfoApiDTO.from_dict(obj["jurisdiction"]) if obj.get("jurisdiction") is not None else None,
            "partner": DebituraWebExternalCustomerAPIModelsCoveragesPartnerInfoApiDTO.from_dict(obj["partner"]) if obj.get("partner") is not None else None,
            "powerOfAttorneyStatus": DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO.from_dict(obj["powerOfAttorneyStatus"]) if obj.get("powerOfAttorneyStatus") is not None else None,
            "errorMessage": obj.get("errorMessage"),
            "ineligibilityReasonCode": obj.get("ineligibilityReasonCode"),
            "applicableMinimumAmount": obj.get("applicableMinimumAmount"),
            "applicableMinimumCurrencyCode": obj.get("applicableMinimumCurrencyCode"),
            "amountCheckUnavailable": obj.get("amountCheckUnavailable")
        })
        return _obj


