# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto(BaseModel):
    """
    DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto
    """ # noqa: E501
    company_name: Annotated[str, Field(min_length=0, strict=True, max_length=200)] = Field(alias="companyName")
    registration_number: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, alias="registrationNumber")
    address: Optional[StrictStr] = None
    zip_code: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, alias="zipCode")
    state: Optional[StrictStr] = None
    city: Annotated[str, Field(min_length=1, strict=True)]
    country_code: Annotated[str, Field(min_length=2, strict=True, max_length=2)] = Field(alias="countryCode")
    office_email: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=250)]] = Field(default=None, alias="officeEmail")
    office_phone: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, alias="officePhone")
    __properties: ClassVar[List[str]] = ["companyName", "registrationNumber", "address", "zipCode", "state", "city", "countryCode", "officeEmail", "officePhone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if registration_number (nullable) is None
        # and model_fields_set contains the field
        if self.registration_number is None and "registration_number" in self.model_fields_set:
            _dict['registrationNumber'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.zip_code is None and "zip_code" in self.model_fields_set:
            _dict['zipCode'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if office_email (nullable) is None
        # and model_fields_set contains the field
        if self.office_email is None and "office_email" in self.model_fields_set:
            _dict['officeEmail'] = None

        # set to None if office_phone (nullable) is None
        # and model_fields_set contains the field
        if self.office_phone is None and "office_phone" in self.model_fields_set:
            _dict['officePhone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "companyName": obj.get("companyName"),
            "registrationNumber": obj.get("registrationNumber"),
            "address": obj.get("address"),
            "zipCode": obj.get("zipCode"),
            "state": obj.get("state"),
            "city": obj.get("city"),
            "countryCode": obj.get("countryCode"),
            "officeEmail": obj.get("officeEmail"),
            "officePhone": obj.get("officePhone")
        })
        return _obj


