# coding: utf-8

"""
    Debitura Customer API

    Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you're representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.

    The version of the OpenAPI document: v1
    Contact: contact@debitura.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from debitura_debt_collection.models.debitura_web_external_api_contracts_v1_cases_requests_preview_debtor_dto import DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
from typing import Optional, Set
from typing_extensions import Self

class DebituraWebExternalApiContractsV1CasesRequestsPreviewCaseRequestApiViewModel(BaseModel):
    """
    Request model for previewing case eligibility, partner assignment, and required actions before actually creating a collection case.              This endpoint allows you to check: - Whether a case would be eligible for collection (partner coverage available) - Which partner would be assigned - What documents need to be signed (SDCA, Power of Attorney) - Estimated pricing with age-based surcharges              Use this to guide users through document signing before final case submission.
    """ # noqa: E501
    amount_to_recover: Union[StrictFloat, StrictInt] = Field(description="The TOTAL amount to recover for this case. This represents the full principal amount across all invoices (if multiple invoices are bundled).              For multi-invoice cases with different ages, you can optionally provide age breakdown fields (AmountToRecoverOver12Months and AmountToRecoverOver24Months) to enable blended age-based pricing.              If age breakdown fields are omitted, the preview will show base pricing without age surcharge calculation.", alias="amountToRecover")
    currency_code: Annotated[str, Field(min_length=3, strict=True, max_length=3)] = Field(description="ISO 4217 currency code for the amount (e.g., \"DKK\", \"EUR\", \"USD\")", alias="currencyCode")
    debtor: DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
    amount_to_recover_over6_months: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="OPTIONAL - MULTI-INVOICE AGE BUCKET PRICING (PRICING ZONE 180-DAY THRESHOLD)              The portion of AmountToRecover that is more than 6 months (180 days) overdue. This includes amounts that are 12+ and 24+ months overdue.              This field is optional and can only be provided alongside AmountToRecoverOver12Months and AmountToRecoverOver24Months. It enables precise pricing tier selection based on the 180-day threshold. When omitted, the system falls back to deriving the threshold from AmountToRecoverOver12Months.              Validation rules: - Must be ≤ AmountToRecover - Must be ≥ AmountToRecoverOver12Months", alias="amountToRecoverOver6Months")
    amount_to_recover_over12_months: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="OPTIONAL - MULTI-INVOICE AGE BUCKET PRICING              The portion of AmountToRecover that is more than 12 months overdue. This includes amounts that are 24+ months overdue.              If provided, AmountToRecoverOver24Months must also be provided. Both fields must be provided together or both omitted.              Used to calculate blended age uplift for multi-invoice cases: - Amount under 12 months = AmountToRecover - AmountToRecoverOver12Months - Amount 12-24 months = AmountToRecoverOver12Months - AmountToRecoverOver24Months - Amount over 24 months = AmountToRecoverOver24Months              Blended uplift formula: ((A12-A24)×10 + A24×20) / AmountToRecover where A12 = AmountToRecoverOver12Months, A24 = AmountToRecoverOver24Months              Validation rules: - Must be ≤ AmountToRecover - Must be ≥ AmountToRecoverOver24Months", alias="amountToRecoverOver12Months")
    amount_to_recover_over24_months: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="OPTIONAL - MULTI-INVOICE AGE BUCKET PRICING              The portion of AmountToRecover that is more than 24 months overdue.              If provided, AmountToRecoverOver12Months must also be provided. Both fields must be provided together or both omitted.              Used to calculate blended age uplift for multi-invoice cases. See AmountToRecoverOver12Months for full details on the calculation.              Validation rules: - Must be ≤ AmountToRecoverOver12Months - Must be ≤ AmountToRecover", alias="amountToRecoverOver24Months")
    due_date: Optional[datetime] = Field(default=None, description="Optional invoice due date. Mutually exclusive with age bucket fields. If provided, Debitura computes the age surcharge internally — no need to calculate age buckets. Cannot be a future date.", alias="dueDate")
    return_url: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="Optional: URL the creditor user should land on after completing any pending signing chain (SDCA upgrade / PoA / JPA / KYC) on the Debitura Creditors app. Embedded, URL-encoded, into `PreviewCaseResponseApiViewModel.Result.SigningHandoff.CombinedSigningUrl` (when at least one signing-related required action is present) and into `BusinessErrorResponseApiDTO.SigningHandoff.CombinedSigningUrl` / `InvoiceDto.SigningHandoff.CombinedSigningUrl` on POST `/cases`.              Must be an absolute http(s) URL. Values that fail validation (relative URLs, non-http schemes, header-injection characters) are silently dropped — the combined URL is still emitted but without the returnUrl query parameter, and the Creditors app falls back to its own safe in-app default landing.              Additive. Existing integrations that omit this field see the same behaviour as before.", alias="returnUrl")
    __properties: ClassVar[List[str]] = ["amountToRecover", "currencyCode", "debtor", "amountToRecoverOver6Months", "amountToRecoverOver12Months", "amountToRecoverOver24Months", "dueDate", "returnUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesRequestsPreviewCaseRequestApiViewModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of debtor
        if self.debtor:
            _dict['debtor'] = self.debtor.to_dict()
        # set to None if amount_to_recover_over6_months (nullable) is None
        # and model_fields_set contains the field
        if self.amount_to_recover_over6_months is None and "amount_to_recover_over6_months" in self.model_fields_set:
            _dict['amountToRecoverOver6Months'] = None

        # set to None if amount_to_recover_over12_months (nullable) is None
        # and model_fields_set contains the field
        if self.amount_to_recover_over12_months is None and "amount_to_recover_over12_months" in self.model_fields_set:
            _dict['amountToRecoverOver12Months'] = None

        # set to None if amount_to_recover_over24_months (nullable) is None
        # and model_fields_set contains the field
        if self.amount_to_recover_over24_months is None and "amount_to_recover_over24_months" in self.model_fields_set:
            _dict['amountToRecoverOver24Months'] = None

        # set to None if due_date (nullable) is None
        # and model_fields_set contains the field
        if self.due_date is None and "due_date" in self.model_fields_set:
            _dict['dueDate'] = None

        # set to None if return_url (nullable) is None
        # and model_fields_set contains the field
        if self.return_url is None and "return_url" in self.model_fields_set:
            _dict['returnUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebituraWebExternalApiContractsV1CasesRequestsPreviewCaseRequestApiViewModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amountToRecover": obj.get("amountToRecover"),
            "currencyCode": obj.get("currencyCode"),
            "debtor": DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto.from_dict(obj["debtor"]) if obj.get("debtor") is not None else None,
            "amountToRecoverOver6Months": obj.get("amountToRecoverOver6Months"),
            "amountToRecoverOver12Months": obj.get("amountToRecoverOver12Months"),
            "amountToRecoverOver24Months": obj.get("amountToRecoverOver24Months"),
            "dueDate": obj.get("dueDate"),
            "returnUrl": obj.get("returnUrl")
        })
        return _obj


