/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Status of an individual contract (SDCA, PoA, or Pricing Appendix).
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesContractItemDto
 */
export interface DebituraWebExternalApiContractsV1CasesContractItemDto {
    /**
     * Whether the contract has been signed.
     * @type {boolean}
     * @memberof DebituraWebExternalApiContractsV1CasesContractItemDto
     */
    'signed'?: boolean;
    /**
     * Whether the contract needs to be re-signed (e.g., due to contract template updates).
     * @type {boolean}
     * @memberof DebituraWebExternalApiContractsV1CasesContractItemDto
     */
    'requiresResigning'?: boolean;
    /**
     * URL where the creditor can sign or re-sign the contract. Null if the contract is signed and current. The URL is context-aware: referral partner tokens get referral onboarding URLs, regular API keys get standard creditor app URLs.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesContractItemDto
     */
    'solutionUrl'?: string | null;
}

