/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Simplified debtor information for case preview. Only includes the minimum fields required for partner routing and eligibility checking.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
 */
export interface DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto {
    /**
     * Debtor type. Valid values: \"Company\" or \"Private\" This affects partner selection as different partners may specialize in B2B vs B2C collection.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
     */
    'type': string;
    /**
     * Country code (ISO 3166-1 alpha-2 format, e.g., \"DK\", \"US\", \"PL\") Used to determine jurisdiction and available collection partners.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
     */
    'countryAlpha2': string;
    /**
     * US state code (e.g., \"CA\", \"NY\") REQUIRED for United States cases only, as US partner coverage is state-specific. Optional for other countries.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsPreviewDebtorDto
     */
    'stateAlpha2'?: string | null;
}

