/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Power of Attorney status (shared DTO for check-eligibility and coverage endpoints).
 * @export
 * @interface DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
 */
export interface DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO {
    /**
     * Whether PoA has been signed for this partner
     * @type {boolean}
     * @memberof DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
     */
    'signed'?: boolean;
    /**
     * Whether PoA needs to be re-signed (new version available)
     * @type {boolean}
     * @memberof DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
     */
    'requiresResigning'?: boolean;
    /**
     * Why re-signing is required (if applicable)
     * @type {string}
     * @memberof DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
     */
    'invalidationReason'?: string | null;
    /**
     * URL to download signed PoA document (null if not signed)
     * @type {string}
     * @memberof DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
     */
    'termsUrl'?: string | null;
    /**
     * URL to sign or re-sign PoA (null if fully signed and valid)
     * @type {string}
     * @memberof DebituraWebExternalCustomerAPIModelsCoveragesPowerOfAttorneyStatusApiDTO
     */
    'solutionUrl'?: string | null;
}

