/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DebituraDomainModelCommunicationCenterChatsChatRole } from './debitura-domain-model-communication-center-chats-chat-role';
// May contain unused imports in some cases
// @ts-ignore
import type { DebituraWebExternalApiContractsV1UsersUserRelationDto } from './debitura-web-external-api-contracts-v1-users-user-relation-dto';

/**
 * 
 * @export
 * @interface DebituraWebExternalApiContractsV1ChatsChatDto
 */
export interface DebituraWebExternalApiContractsV1ChatsChatDto {
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'dateCreated'?: string;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'dateUpdated'?: string | null;
    /**
     * 
     * @type {DebituraDomainModelCommunicationCenterChatsChatRole}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'role'?: DebituraDomainModelCommunicationCenterChatsChatRole;
    /**
     * Human-readable label for the role (e.g., \"Partner\", \"Creditor\", \"Managed by partner\"). Companion to Debitura.Web.ExternalApi.Contracts.V1.Chats.ChatDto.Role — always present when Role is set.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'roleLabel'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'message'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'isSeen'?: boolean;
    /**
     * 
     * @type {DebituraWebExternalApiContractsV1UsersUserRelationDto}
     * @memberof DebituraWebExternalApiContractsV1ChatsChatDto
     */
    'user'?: DebituraWebExternalApiContractsV1UsersUserRelationDto;
}



