/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * V1 Lead Quote DTO for external customer APIs (summary view)
 * @export
 * @interface DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
 */
export interface DebituraWebExternalApiContractsV1LeadsLeadQuoteDto {
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'quoteId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'quoteRequestId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'partnerId'?: string;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'partnerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'status': string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'agreementType': string | null;
    /**
     * 
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'hourlyRate'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'hourlyEstimated'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'flatFeeEstimate'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'successFee'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'hybridEstimate'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'proposedSolution'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'partnerWhyUsSection'?: string | null;
    /**
     * The case phase this quote offers to work in (Pre-legal / Legal / Enforcement). Null = unspecified.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'phase'?: string | null;
    /**
     * Whether declining stops the case (Recommendation / Required). v1: display only. Null = unspecified.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'offerNature'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'currency': string | null;
    /**
     * 
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1LeadsLeadQuoteDto
     */
    'dateCreated'?: string;
}

