/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DebituraWebExternalApiContractsV1CasesBusinessErrorApiDTO } from './debitura-web-external-api-contracts-v1-cases-business-error-api-dto';

/**
 * Generic structured error response for API endpoints.              Dual-write design: existing fields (Debitura.Web.ExternalApi.Contracts.V1.Errors.ApiErrorResponseDto.Error / Debitura.Web.ExternalApi.Contracts.V1.Errors.ApiErrorResponseDto.Message etc.) are preserved for backward compatibility alongside the canonical Debitura.Web.ExternalApi.Contracts.V1.Errors.ApiErrorResponseDto.BusinessErrors array, allowing consumers to migrate at their own pace.
 * @export
 * @interface DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto
 */
export interface DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto {
    /**
     * Short human-readable error label (legacy field — preserved for backward compatibility).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto
     */
    'error'?: string | null;
    /**
     * Human-readable error description (legacy field — preserved for backward compatibility).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto
     */
    'message'?: string | null;
    /**
     * Canonical structured error array. Consumers should migrate to reading this field.
     * @type {Array<DebituraWebExternalApiContractsV1CasesBusinessErrorApiDTO>}
     * @memberof DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto
     */
    'businessErrors'?: Array<DebituraWebExternalApiContractsV1CasesBusinessErrorApiDTO> | null;
}

