/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Geographic jurisdiction information for the case.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesJurisdictionDto
 */
export interface DebituraWebExternalApiContractsV1CasesJurisdictionDto {
    /**
     * Internal jurisdiction identifier.
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1CasesJurisdictionDto
     */
    'id'?: number;
    /**
     * Display name of the jurisdiction (e.g., \"Denmark\", \"United States - California\").
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesJurisdictionDto
     */
    'name'?: string | null;
    /**
     * ISO 3166-1 alpha-2 country code.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesJurisdictionDto
     */
    'countryAlpha2'?: string | null;
    /**
     * ISO 3166-2 state/region code (only for countries with state-level routing like the US).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesJurisdictionDto
     */
    'stateAlpha2'?: string | null;
}

