/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single extension event in the exclusive period chain.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesExclusivePeriodExtensionDto
 */
export interface DebituraWebExternalApiContractsV1CasesExclusivePeriodExtensionDto {
    /**
     * What triggered this extension: PromiseToPay, PaymentAgreement, Payment, or Manual.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesExclusivePeriodExtensionDto
     */
    'type'?: string | null;
    /**
     * When the extension period started (i.e. when the trigger event occurred).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesExclusivePeriodExtensionDto
     */
    'eventDate'?: string;
    /**
     * The new period end date after this extension was applied.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesExclusivePeriodExtensionDto
     */
    'newEndDate'?: string;
}

