/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for POST /test/webhooks/fire.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesRequestsFireWebhookRequest
 */
export interface DebituraWebExternalApiContractsV1CasesRequestsFireWebhookRequest {
    /**
     * The webhook event type to fire (e.g. \"case.updated\", \"payment.created\"). Must be a valid event type for the calling API — refer to each API\'s documentation for the supported list (Collection Partner and Customer API accept different sets).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsFireWebhookRequest
     */
    'event': string | null;
    /**
     * The ID of the test case to use as the event source.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsFireWebhookRequest
     */
    'caseId': string;
    /**
     * Optional — the specific subscription ID to fire to. If omitted, fires to all active test subscriptions for the calling API subscriber that are registered for the given event type.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsFireWebhookRequest
     */
    'subscriptionId'?: string | null;
}

