/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from POST /test/cases/{id}/advance.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesAdvanceTestCaseResponse
 */
export interface DebituraWebExternalApiContractsV1CasesAdvanceTestCaseResponse {
    /**
     * True if the case was advanced in this call; false if it was already at or past the target state (no-op).
     * @type {boolean}
     * @memberof DebituraWebExternalApiContractsV1CasesAdvanceTestCaseResponse
     */
    'advanced'?: boolean;
    /**
     * The current state of the case after this call. One of: \"Active\", \"Closed:Paid\", \"Closed:NoPayment\", \"Closed\" (for other close codes).
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesAdvanceTestCaseResponse
     */
    'state'?: string | null;
}

