/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single unpaid invoice belonging to the claim. Claim lines are a pricing input only: they are used to derive the claim total and the cumulative age buckets, and are then discarded. They are not stored and are never shown to the collecting partner — put a per-invoice breakdown in Comments if the partner needs one.
 * @export
 * @interface DebituraWebExternalApiContractsV1CasesRequestsClaimLineDto
 */
export interface DebituraWebExternalApiContractsV1CasesRequestsClaimLineDto {
    /**
     * Payment deadline of this invoice. Provide date only without time component. Must be on or after 2000-01-01 and must not be in the future.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsClaimLineDto
     */
    'dueDate': string | null;
    /**
     * The outstanding balance on this invoice in the case currency — what the debtor still owes on it, already net of any payments the debtor has made and net of any credit notes issued against it. This is not the invoice\'s original face value. Must be greater than zero with at most 2 decimal places; omit invoices that are fully settled.
     * @type {number}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsClaimLineDto
     */
    'amount': number;
    /**
     * Optional: your own invoice number for this line. Used only to make validation errors readable and to reject the same invoice being sent twice. It is not stored and not shown to anyone.
     * @type {string}
     * @memberof DebituraWebExternalApiContractsV1CasesRequestsClaimLineDto
     */
    'reference'?: string | null;
}

