/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto } from '../models';
// @ts-ignore
import type { DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO } from '../models';
// @ts-ignore
import type { DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO } from '../models';
// @ts-ignore
import type { DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO } from '../models';
/**
 * CoverageApi - axios parameter creator
 * @export
 */
export const CoverageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * **Determine if a case can be submitted and get partner + PoA status.**  **Request Fields:** - CountryAlpha2 (required) - Debtor country (e.g., \'DK\', \'US\', \'DE\') - StateAlpha2 (conditional) - Required for US debtors (e.g., \'CA\', \'NY\') - DebtorType (required) - \'Company\' or \'Private\' - Amount (required) - Amount to recover - CurrencyCode (required) - Currency (e.g., \'USD\', \'EUR\', \'DKK\')  **Response:** - IsEligible (boolean) - Whether case can be submitted - Partner - Specific partner that will handle this case - PowerOfAttorneyStatus - PoA signing status for the matched partner  **Note:** Does NOT check SDCA status. Use GET /contracts/debt-collection/status for that.
         * @summary Check case eligibility and get assigned partner
         * @param {DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO} [debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageCheckEligibilityPost: async (debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO?: DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coverage/check-eligibility`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns complete coverage information for all jurisdictions where Debitura operates, including power of attorney signing status and solution URLs.
         * @summary List all jurisdiction coverage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coverage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a single jurisdiction with its geographic information, assigned collection partner, and power of attorney signing status.
         * @summary Get jurisdiction coverage by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('coverageIdGet', 'id', id)
            const localVarPath = `/coverage/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {string} [q] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        coverageSearchGet: async (q?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coverage/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {string} [q] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        coverageSearchGet_1: async (q?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/coverage/:search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoverageApi - functional programming interface
 * @export
 */
export const CoverageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoverageApiAxiosParamCreator(configuration)
    return {
        /**
         * **Determine if a case can be submitted and get partner + PoA status.**  **Request Fields:** - CountryAlpha2 (required) - Debtor country (e.g., \'DK\', \'US\', \'DE\') - StateAlpha2 (conditional) - Required for US debtors (e.g., \'CA\', \'NY\') - DebtorType (required) - \'Company\' or \'Private\' - Amount (required) - Amount to recover - CurrencyCode (required) - Currency (e.g., \'USD\', \'EUR\', \'DKK\')  **Response:** - IsEligible (boolean) - Whether case can be submitted - Partner - Specific partner that will handle this case - PowerOfAttorneyStatus - PoA signing status for the matched partner  **Note:** Does NOT check SDCA status. Use GET /contracts/debt-collection/status for that.
         * @summary Check case eligibility and get assigned partner
         * @param {DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO} [debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coverageCheckEligibilityPost(debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO?: DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageCheckEligibilityPost(debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoverageApi.coverageCheckEligibilityPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns complete coverage information for all jurisdictions where Debitura operates, including power of attorney signing status and solution URLs.
         * @summary List all jurisdiction coverage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coverageGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoverageApi.coverageGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a single jurisdiction with its geographic information, assigned collection partner, and power of attorney signing status.
         * @summary Get jurisdiction coverage by ID
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async coverageIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoverageApi.coverageIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {string} [q] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async coverageSearchGet(q?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageSearchGet(q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoverageApi.coverageSearchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {string} [q] 
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async coverageSearchGet_1(q?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.coverageSearchGet_1(q, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoverageApi.coverageSearchGet_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoverageApi - factory interface
 * @export
 */
export const CoverageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoverageApiFp(configuration)
    return {
        /**
         * **Determine if a case can be submitted and get partner + PoA status.**  **Request Fields:** - CountryAlpha2 (required) - Debtor country (e.g., \'DK\', \'US\', \'DE\') - StateAlpha2 (conditional) - Required for US debtors (e.g., \'CA\', \'NY\') - DebtorType (required) - \'Company\' or \'Private\' - Amount (required) - Amount to recover - CurrencyCode (required) - Currency (e.g., \'USD\', \'EUR\', \'DKK\')  **Response:** - IsEligible (boolean) - Whether case can be submitted - Partner - Specific partner that will handle this case - PowerOfAttorneyStatus - PoA signing status for the matched partner  **Note:** Does NOT check SDCA status. Use GET /contracts/debt-collection/status for that.
         * @summary Check case eligibility and get assigned partner
         * @param {CoverageApiCoverageCheckEligibilityPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageCheckEligibilityPost(requestParameters: CoverageApiCoverageCheckEligibilityPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityResponseApiDTO> {
            return localVarFp.coverageCheckEligibilityPost(requestParameters.debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns complete coverage information for all jurisdictions where Debitura operates, including power of attorney signing status and solution URLs.
         * @summary List all jurisdiction coverage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO>> {
            return localVarFp.coverageGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a single jurisdiction with its geographic information, assigned collection partner, and power of attorney signing status.
         * @summary Get jurisdiction coverage by ID
         * @param {CoverageApiCoverageIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        coverageIdGet(requestParameters: CoverageApiCoverageIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO> {
            return localVarFp.coverageIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {CoverageApiCoverageSearchGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        coverageSearchGet(requestParameters: CoverageApiCoverageSearchGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO> {
            return localVarFp.coverageSearchGet(requestParameters.q, options).then((request) => request(axios, basePath));
        },
        /**
         * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
         * @summary [DEPRECATED] Search for jurisdiction coverage
         * @param {CoverageApiCoverageSearchGet0Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        coverageSearchGet_1(requestParameters: CoverageApiCoverageSearchGet0Request = {}, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalCustomerAPIModelsCoveragesCoverageItemApiDTO> {
            return localVarFp.coverageSearchGet_1(requestParameters.q, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for coverageCheckEligibilityPost operation in CoverageApi.
 * @export
 * @interface CoverageApiCoverageCheckEligibilityPostRequest
 */
export interface CoverageApiCoverageCheckEligibilityPostRequest {
    /**
     * 
     * @type {DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO}
     * @memberof CoverageApiCoverageCheckEligibilityPost
     */
    readonly debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO?: DebituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO
}

/**
 * Request parameters for coverageIdGet operation in CoverageApi.
 * @export
 * @interface CoverageApiCoverageIdGetRequest
 */
export interface CoverageApiCoverageIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof CoverageApiCoverageIdGet
     */
    readonly id: number
}

/**
 * Request parameters for coverageSearchGet operation in CoverageApi.
 * @export
 * @interface CoverageApiCoverageSearchGetRequest
 */
export interface CoverageApiCoverageSearchGetRequest {
    /**
     * 
     * @type {string}
     * @memberof CoverageApiCoverageSearchGet
     */
    readonly q?: string
}

/**
 * Request parameters for coverageSearchGet_1 operation in CoverageApi.
 * @export
 * @interface CoverageApiCoverageSearchGet0Request
 */
export interface CoverageApiCoverageSearchGet0Request {
    /**
     * 
     * @type {string}
     * @memberof CoverageApiCoverageSearchGet0
     */
    readonly q?: string
}

/**
 * CoverageApi - object-oriented interface
 * @export
 * @class CoverageApi
 * @extends {BaseAPI}
 */
export class CoverageApi extends BaseAPI {
    /**
     * **Determine if a case can be submitted and get partner + PoA status.**  **Request Fields:** - CountryAlpha2 (required) - Debtor country (e.g., \'DK\', \'US\', \'DE\') - StateAlpha2 (conditional) - Required for US debtors (e.g., \'CA\', \'NY\') - DebtorType (required) - \'Company\' or \'Private\' - Amount (required) - Amount to recover - CurrencyCode (required) - Currency (e.g., \'USD\', \'EUR\', \'DKK\')  **Response:** - IsEligible (boolean) - Whether case can be submitted - Partner - Specific partner that will handle this case - PowerOfAttorneyStatus - PoA signing status for the matched partner  **Note:** Does NOT check SDCA status. Use GET /contracts/debt-collection/status for that.
     * @summary Check case eligibility and get assigned partner
     * @param {CoverageApiCoverageCheckEligibilityPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverageApi
     */
    public coverageCheckEligibilityPost(requestParameters: CoverageApiCoverageCheckEligibilityPostRequest = {}, options?: RawAxiosRequestConfig) {
        return CoverageApiFp(this.configuration).coverageCheckEligibilityPost(requestParameters.debituraWebExternalCustomerAPIModelsCoveragesCaseEligibilityRequestApiDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns complete coverage information for all jurisdictions where Debitura operates, including power of attorney signing status and solution URLs.
     * @summary List all jurisdiction coverage
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverageApi
     */
    public coverageGet(options?: RawAxiosRequestConfig) {
        return CoverageApiFp(this.configuration).coverageGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a single jurisdiction with its geographic information, assigned collection partner, and power of attorney signing status.
     * @summary Get jurisdiction coverage by ID
     * @param {CoverageApiCoverageIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoverageApi
     */
    public coverageIdGet(requestParameters: CoverageApiCoverageIdGetRequest, options?: RawAxiosRequestConfig) {
        return CoverageApiFp(this.configuration).coverageIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
     * @summary [DEPRECATED] Search for jurisdiction coverage
     * @param {CoverageApiCoverageSearchGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof CoverageApi
     */
    public coverageSearchGet(requestParameters: CoverageApiCoverageSearchGetRequest = {}, options?: RawAxiosRequestConfig) {
        return CoverageApiFp(this.configuration).coverageSearchGet(requestParameters.q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ⚠️ **DEPRECATED:** Use POST /coverage/check-eligibility instead.
     * @summary [DEPRECATED] Search for jurisdiction coverage
     * @param {CoverageApiCoverageSearchGet0Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof CoverageApi
     */
    public coverageSearchGet_1(requestParameters: CoverageApiCoverageSearchGet0Request = {}, options?: RawAxiosRequestConfig) {
        return CoverageApiFp(this.configuration).coverageSearchGet_1(requestParameters.q, options).then((request) => request(this.axios, this.basePath));
    }
}

