/* tslint:disable */
/* eslint-disable */
/**
 * Debitura Customer API
 * Welcome to the Debitura Customer API, your gateway to seamlessly integrating your debt collection workflow with our platform. Debitura connects customers with trusted debt collection firms specializing in pre-legal debt recovery. With this API, you can easily upload cases, track their status, and manage your debt collection process efficiently. For any support or inquiries, please reach out to us at contact@debitura.com. To setup an API key, log into your Debitura account and go here: https://app.debitura.com/CreditorApiKey  📖 Full documentation, guides, and integration walkthroughs: https://docs.debitura.com/clients  NOTE: if you\'re representing a platform and want to provide this feature for your customers, you need a different API. Please contact us.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@debitura.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto } from '../models';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1DivisionsDivisionDto } from '../models';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1DivisionsDivisionListDto } from '../models';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto } from '../models';
// @ts-ignore
import type { DebituraWebExternalApiContractsV1ErrorsApiErrorResponseDto } from '../models';
/**
 * DivisionsApi - axios parameter creator
 * @export
 */
export const DivisionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns a paginated list of divisions for the authenticated creditor.  By default, archived divisions are excluded. Set `includeArchived=true` to include them.
         * @summary List divisions for the authenticated creditor.
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {boolean} [includeArchived] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsGet: async (page?: number, pageSize?: number, includeArchived?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/divisions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (includeArchived !== undefined) {
                localVarQueryParameter['includeArchived'] = includeArchived;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdArchivePost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('divisionsIdArchivePost', 'id', id)
            const localVarPath = `/divisions/{id}/archive`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes a division.  **Important:** A division cannot be deleted if it is referenced by active cases. If you need to deactivate a division that has cases, use the archive endpoint instead.
         * @summary Delete a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('divisionsIdDelete', 'id', id)
            const localVarPath = `/divisions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns details of a specific division. The division must belong to the authenticated creditor.
         * @summary Get a single division by ID.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('divisionsIdGet', 'id', id)
            const localVarPath = `/divisions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Replaces all fields of a division. All required fields must be provided.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')
         * @summary Update a division.
         * @param {string} id 
         * @param {DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto} [debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdPut: async (id: string, debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('divisionsIdPut', 'id', id)
            const localVarPath = `/divisions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdarchivePost: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('divisionsIdarchivePost', 'id', id)
            const localVarPath = `/divisions/{id}:archive`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new division for the authenticated creditor.  Divisions allow creditors to organize cases under different business units, branches, or departments.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')  **Optional Fields:** - registrationNumber - Company registration number (CVR, VAT, etc.) - address, zipCode, state - Full address details - officeEmail, officePhone - Contact information
         * @summary Create a new division.
         * @param {string} [idempotencyKey] Optional idempotency key (max 255 characters) for safely retrying this request. If a previous request used the same key with an identical body, the original terminal response is replayed verbatim. Reusing the key with a different body returns 422 with &#x60;Type: \&quot;IdempotencyConflict\&quot;&#x60;. Field-level 400 validation errors are not stored, so you may fix the request and retry with the same key.
         * @param {DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto} [debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsPost: async (idempotencyKey?: string, debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/divisions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKey required
            await setApiKeyToObject(localVarHeaderParameter, "XApiKey", configuration)

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DivisionsApi - functional programming interface
 * @export
 */
export const DivisionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DivisionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns a paginated list of divisions for the authenticated creditor.  By default, archived divisions are excluded. Set `includeArchived=true` to include them.
         * @summary List divisions for the authenticated creditor.
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {boolean} [includeArchived] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsGet(page?: number, pageSize?: number, includeArchived?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionListDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsGet(page, pageSize, includeArchived, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsIdArchivePost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsIdArchivePost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsIdArchivePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes a division.  **Important:** A division cannot be deleted if it is referenced by active cases. If you need to deactivate a division that has cases, use the archive endpoint instead.
         * @summary Delete a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns details of a specific division. The division must belong to the authenticated creditor.
         * @summary Get a single division by ID.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Replaces all fields of a division. All required fields must be provided.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')
         * @summary Update a division.
         * @param {string} id 
         * @param {DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto} [debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsIdPut(id: string, debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsIdPut(id, debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsIdarchivePost(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsIdarchivePost(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsIdarchivePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new division for the authenticated creditor.  Divisions allow creditors to organize cases under different business units, branches, or departments.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')  **Optional Fields:** - registrationNumber - Company registration number (CVR, VAT, etc.) - address, zipCode, state - Full address details - officeEmail, officePhone - Contact information
         * @summary Create a new division.
         * @param {string} [idempotencyKey] Optional idempotency key (max 255 characters) for safely retrying this request. If a previous request used the same key with an identical body, the original terminal response is replayed verbatim. Reusing the key with a different body returns 422 with &#x60;Type: \&quot;IdempotencyConflict\&quot;&#x60;. Field-level 400 validation errors are not stored, so you may fix the request and retry with the same key.
         * @param {DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto} [debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async divisionsPost(idempotencyKey?: string, debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.divisionsPost(idempotencyKey, debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DivisionsApi.divisionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DivisionsApi - factory interface
 * @export
 */
export const DivisionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DivisionsApiFp(configuration)
    return {
        /**
         * Returns a paginated list of divisions for the authenticated creditor.  By default, archived divisions are excluded. Set `includeArchived=true` to include them.
         * @summary List divisions for the authenticated creditor.
         * @param {DivisionsApiDivisionsGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsGet(requestParameters: DivisionsApiDivisionsGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionListDto> {
            return localVarFp.divisionsGet(requestParameters.page, requestParameters.pageSize, requestParameters.includeArchived, options).then((request) => request(axios, basePath));
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {DivisionsApiDivisionsIdArchivePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdArchivePost(requestParameters: DivisionsApiDivisionsIdArchivePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto> {
            return localVarFp.divisionsIdArchivePost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes a division.  **Important:** A division cannot be deleted if it is referenced by active cases. If you need to deactivate a division that has cases, use the archive endpoint instead.
         * @summary Delete a division.
         * @param {DivisionsApiDivisionsIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdDelete(requestParameters: DivisionsApiDivisionsIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.divisionsIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns details of a specific division. The division must belong to the authenticated creditor.
         * @summary Get a single division by ID.
         * @param {DivisionsApiDivisionsIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdGet(requestParameters: DivisionsApiDivisionsIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto> {
            return localVarFp.divisionsIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Replaces all fields of a division. All required fields must be provided.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')
         * @summary Update a division.
         * @param {DivisionsApiDivisionsIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdPut(requestParameters: DivisionsApiDivisionsIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto> {
            return localVarFp.divisionsIdPut(requestParameters.id, requestParameters.debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
         * @summary Archive a division.
         * @param {DivisionsApiDivisionsIdarchivePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsIdarchivePost(requestParameters: DivisionsApiDivisionsIdarchivePostRequest, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto> {
            return localVarFp.divisionsIdarchivePost(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new division for the authenticated creditor.  Divisions allow creditors to organize cases under different business units, branches, or departments.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')  **Optional Fields:** - registrationNumber - Company registration number (CVR, VAT, etc.) - address, zipCode, state - Full address details - officeEmail, officePhone - Contact information
         * @summary Create a new division.
         * @param {DivisionsApiDivisionsPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        divisionsPost(requestParameters: DivisionsApiDivisionsPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<DebituraWebExternalApiContractsV1DivisionsDivisionDto> {
            return localVarFp.divisionsPost(requestParameters.idempotencyKey, requestParameters.debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for divisionsGet operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsGetRequest
 */
export interface DivisionsApiDivisionsGetRequest {
    /**
     * 
     * @type {number}
     * @memberof DivisionsApiDivisionsGet
     */
    readonly page?: number

    /**
     * 
     * @type {number}
     * @memberof DivisionsApiDivisionsGet
     */
    readonly pageSize?: number

    /**
     * 
     * @type {boolean}
     * @memberof DivisionsApiDivisionsGet
     */
    readonly includeArchived?: boolean
}

/**
 * Request parameters for divisionsIdArchivePost operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsIdArchivePostRequest
 */
export interface DivisionsApiDivisionsIdArchivePostRequest {
    /**
     * 
     * @type {string}
     * @memberof DivisionsApiDivisionsIdArchivePost
     */
    readonly id: string
}

/**
 * Request parameters for divisionsIdDelete operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsIdDeleteRequest
 */
export interface DivisionsApiDivisionsIdDeleteRequest {
    /**
     * 
     * @type {string}
     * @memberof DivisionsApiDivisionsIdDelete
     */
    readonly id: string
}

/**
 * Request parameters for divisionsIdGet operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsIdGetRequest
 */
export interface DivisionsApiDivisionsIdGetRequest {
    /**
     * 
     * @type {string}
     * @memberof DivisionsApiDivisionsIdGet
     */
    readonly id: string
}

/**
 * Request parameters for divisionsIdPut operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsIdPutRequest
 */
export interface DivisionsApiDivisionsIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof DivisionsApiDivisionsIdPut
     */
    readonly id: string

    /**
     * 
     * @type {DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto}
     * @memberof DivisionsApiDivisionsIdPut
     */
    readonly debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto
}

/**
 * Request parameters for divisionsIdarchivePost operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsIdarchivePostRequest
 */
export interface DivisionsApiDivisionsIdarchivePostRequest {
    /**
     * 
     * @type {string}
     * @memberof DivisionsApiDivisionsIdarchivePost
     */
    readonly id: string
}

/**
 * Request parameters for divisionsPost operation in DivisionsApi.
 * @export
 * @interface DivisionsApiDivisionsPostRequest
 */
export interface DivisionsApiDivisionsPostRequest {
    /**
     * Optional idempotency key (max 255 characters) for safely retrying this request. If a previous request used the same key with an identical body, the original terminal response is replayed verbatim. Reusing the key with a different body returns 422 with &#x60;Type: \&quot;IdempotencyConflict\&quot;&#x60;. Field-level 400 validation errors are not stored, so you may fix the request and retry with the same key.
     * @type {string}
     * @memberof DivisionsApiDivisionsPost
     */
    readonly idempotencyKey?: string

    /**
     * 
     * @type {DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto}
     * @memberof DivisionsApiDivisionsPost
     */
    readonly debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto?: DebituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto
}

/**
 * DivisionsApi - object-oriented interface
 * @export
 * @class DivisionsApi
 * @extends {BaseAPI}
 */
export class DivisionsApi extends BaseAPI {
    /**
     * Returns a paginated list of divisions for the authenticated creditor.  By default, archived divisions are excluded. Set `includeArchived=true` to include them.
     * @summary List divisions for the authenticated creditor.
     * @param {DivisionsApiDivisionsGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsGet(requestParameters: DivisionsApiDivisionsGetRequest = {}, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsGet(requestParameters.page, requestParameters.pageSize, requestParameters.includeArchived, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
     * @summary Archive a division.
     * @param {DivisionsApiDivisionsIdArchivePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsIdArchivePost(requestParameters: DivisionsApiDivisionsIdArchivePostRequest, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsIdArchivePost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes a division.  **Important:** A division cannot be deleted if it is referenced by active cases. If you need to deactivate a division that has cases, use the archive endpoint instead.
     * @summary Delete a division.
     * @param {DivisionsApiDivisionsIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsIdDelete(requestParameters: DivisionsApiDivisionsIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns details of a specific division. The division must belong to the authenticated creditor.
     * @summary Get a single division by ID.
     * @param {DivisionsApiDivisionsIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsIdGet(requestParameters: DivisionsApiDivisionsIdGetRequest, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces all fields of a division. All required fields must be provided.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')
     * @summary Update a division.
     * @param {DivisionsApiDivisionsIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsIdPut(requestParameters: DivisionsApiDivisionsIdPutRequest, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsIdPut(requestParameters.id, requestParameters.debituraWebExternalApiContractsV1DivisionsUpdateDivisionRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Archives a division, making it inactive. Archived divisions are excluded from list results by default.  **Important:** This action is irreversible. Archived divisions can still be referenced by existing cases.
     * @summary Archive a division.
     * @param {DivisionsApiDivisionsIdarchivePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsIdarchivePost(requestParameters: DivisionsApiDivisionsIdarchivePostRequest, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsIdarchivePost(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new division for the authenticated creditor.  Divisions allow creditors to organize cases under different business units, branches, or departments.  **Required Fields:** - companyName - Name of the division - city - City where the division is located - countryCode - ISO 3166-1 alpha-2 country code (e.g. \'US\', \'DE\', \'DK\')  **Optional Fields:** - registrationNumber - Company registration number (CVR, VAT, etc.) - address, zipCode, state - Full address details - officeEmail, officePhone - Contact information
     * @summary Create a new division.
     * @param {DivisionsApiDivisionsPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DivisionsApi
     */
    public divisionsPost(requestParameters: DivisionsApiDivisionsPostRequest = {}, options?: RawAxiosRequestConfig) {
        return DivisionsApiFp(this.configuration).divisionsPost(requestParameters.idempotencyKey, requestParameters.debituraWebExternalApiContractsV1DivisionsCreateDivisionRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

